### ISSUE TITLE
crashes on start with segmentation fault

### ISSUE THREAD

**Issue by escalade** [libretro/vice-libretro#1]
Here's the last part of the strace:

`write(1, " 0  x64\n", 8 0  x64
)                = 8
write(1, " 1  /storage/roms/c64/LNINJA2A.D"..., 35 1  /storage/roms/c64/LNINJA2A.D64
) = 35
open("./vicelog.txt", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 12
brk(0x2768000)                          = 0x2768000
brk(0x279c000)                          = 0x279c000
write(1, "bootp:(/storage/roms/bios/data)\n", 32bootp:(/storage/roms/bios/data)
) = 32
getcwd("/storage", 128)                 = 9
access("/storage/roms/bios/data/C64/sdl_sym.vkm", R_OK) = 0
open("/storage/roms/bios/data/C64/sdl_sym.vkm", O_RDONLY) = 13
close(13)                               = 0
access("/storage/roms/bios/data/C64/sdl_sym.vkm", R_OK) = 0
open("/storage/roms/bios/data/C64/sdl_sym.vkm", O_RDONLY) = 13
close(13)                               = 0
access("/storage/roms/bios/data/C64/sdl_pos.vkm", R_OK) = 0
open("/storage/roms/bios/data/C64/sdl_pos.vkm", O_RDONLY) = 13
close(13)                               = 0
access("/storage/roms/bios/data/C64/sdl_sym.vkm", R_OK) = 0
open("/storage/roms/bios/data/C64/sdl_sym.vkm", O_RDONLY) = 13
close(13)                               = 0
brk(0x28b9000)                          = 0x28b9000
brk(0x29b9000)                          = 0x29b9000
brk(0x2ab9000)                          = 0x2ab9000
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault
`

My retroarch.cfg: http://sprunge.us/AUSC

Intel NUC, LibreELEC 8. RetroArch ~1.5 (32a5c1a).

**Comment by r-type** [comment]
be more precise. provide all the details ,full retroarch logs , system ,distribution,cpu. ect

**Comment by twinaphex** [comment]
Hi there escalade,

the 'data' directory needs to be in your system directory.

**Comment by r-type** [comment]
yes ,good catch, I miss that ,
from his conf system is system_directory = "~/roms/bios"
and from his log data is in /storage/roms/bios

**Comment by escalade** [comment]
This is LibreELEC, the home directory is /storage. The system directory is populated with the full data directory. It's a NUC D54250WYK with a i5-4250U CPU.

Full RetroArch log: http://sprunge.us/PbVO

**Comment by r-type** [comment]
could you also provide the vicelog.txt if any?

**Comment by escalade** [comment]
It's there but it's empty :(

**Comment by escalade** [comment]
I found the issue: LibreELEC's cross compiling toolchain uses LTO by default, disabling LTO solves the segmentation fault. The core boots now, but I can't seem to load a disk. After the LOAD command is run, the error is "?DEVICE NOT PRESENT  ERROR".

**Comment by r-type** [comment]
go to RA quick menu and try to change vice_Drive8Typeto 1541 or 1542

**Comment by escalade** [comment]
Same issue.

**Comment by r-type** [comment]
with every game ? can you post the vicelog.txt should be not empty now.

**Comment by escalade** [comment]
Yes, every game (although tapes work fine). I managed to get it working by enabling "DriveTrueEmulation" and setting type to 1541. Works although loading is a bit slow.

Here's the vicelog without DriveTrueEmulation: http://sprunge.us/NQCY

**Comment by r-type** [comment]
yes without DriveTrueEmulation game loading not working fine.

For the speed loading it's because  retroarch keep framerate to 50fps( because sync with audio) ,
I use input_hold_fast_forward keys to speed up loading (400-500% instead of 100%) 
and keep the key hold until load is finish , then framerate revert to 100% and audio is fine.

Another way to load game is to use ide64 and then load them from virtual hdd.
it's tricky to setup http://www.ide64.org/vice_ide64_howto_rev2.txt but then you can load them from hd
or even from usb host server.

**Comment by escalade** [comment]
I noticed joystick wasn't working until I set "Retro joy0" to on as well, perhaps these defaults should be changed?   Does two joysticks work at all?

One more question, any possibility of getting refresh rate switching in RA? Some emulators (VICE, UAE) have much better vsync with 50Hz refresh rate. I can change that with xrandr before launching a game when using X, but haven't found a way for KMS/EGL yet.

Oh, and feel free to tell me to use the forum instead and close this issue :)

**Comment by r-type** [comment]
Yes maybe better on by default.
for all the vice setting, I personally  use a vicerc , that let me tweak the vice emulator as i want. (command line is also an option if your are convenient with).
BTW ,yes maybe the forum will be a better place.
and for the refresh question I let the RA team answer as they know better than me on RA.
