### ISSUE TITLE
two player support and keyboard suggestion

### ISSUE THREAD

**Issue by hoderer** [libretro/vice-libretro#10]
Thanks for your great module.

I noticed that the pushes on the letters of the keyboard are recognized as a fire button push, too - it would be better if the push on the button would be isolated from the game, so that the game only recognizes the key-push. Another thing: I noticed on the SNES mini that a few letters on the keyboard are not recognized by the game. For example the letter "n" or the "run/stop"-key. Don't know if that is device related. Does the keyboard work on the NES mini flawlessly?

also save states and 2nd controller doesnt work on the SNES mini. I really hope that's on the to do-list.

Thanks for your work!

**Comment by rsn8887** [comment]
second controller works now.

**Comment by rsn8887** [comment]
You might want to retest multiplayer support using latest nightly. Up to five controllers work now at least on VitaTV. Emulated multiplayer adapter can be selected in quick menu - tested working with Bomb-Mania playing with three players simultaneously on vita tv.

**Comment by rsn8887** [comment]
Fixed by PR #73
