### ISSUE TITLE
Feature Request - core option - no borders

### ISSUE THREAD

**Issue by ebbi2017** [libretro/vice-libretro#11]
Heya,

first thanks for the great vice emu!

It would be cool to have a setting to remove the borders optionally as a core option.

Thanks for your efforts making things better,

ebbi

**Comment by modeler** [comment]
You can crop the borders out using the misc/image_adjustment shader if you wish. This is a better solution than the "No borders" mode in stand-alone VICE, as the borders are still emulated (many programs crash without them).
