### ISSUE TITLE
Numpad 5 internally mapped to fire

### ISSUE THREAD

**Issue by Zombeaver** [libretro/vice-libretro#111]
In the newest version of the core, numpad 5 seems to have some kind of internal mapping to the fire button which I can't seem to remove. This wasn't the case in earlier versions. I've always had numpad 8456 assigned as the keyboard controls for up, left, down, and right on the joystick, but now 5 is sending both a down and a fire input. Numpad 2 sends a down input as well. I haven't been able to figure out a way around this as nothing in the UI seems to have numpad 5 listed as the fire button.

I'm using a simple Numpad5::Numpad2 AHK script as a temporary workaround.

**Comment by rsn8887** [comment]
yes there's currently a hard-coded keypad mapping for some keyrah thing or so? It maps player 1 and player 2 input to various keypad keys. @sonninnos should be able to explain why it is there. I think we might be able to remove it if it interferes with the user-mappings, but wait for @sonninnos comment.

**Comment by Zombeaver** [comment]
Awesome, thank you!

**Comment by rsn8887** [comment]
This is fixed by https://github.com/libretro/vice-libretro/commit/ef86cd908314b3f1c45e29fb70d36341e04860e0

The fix should be in next nightly. There is now an option called "Keyrah keypad mappings" which is now disabled by default.
