### ISSUE TITLE
No way to set core option vice_mapper values to null/blank

### ISSUE THREAD

**Issue by Zombeaver** [libretro/vice-libretro#112]
This has been an issue for a while, and isn't the result of any recent updates, but there still isn't a way to set the vice_mapper core options (vice_mapper_y = , vice_mapper_x = , etc.) to a null/blank value. I've always used a value of RETROK_LSHIFT for the ones that I didn't want to do anything, but a proper blank option would be preferable. This already exists for "vice_mapper_select" which defaults to a value of "---" but that value doesn't work in any of the other fields, and they go back to a default value after starting.

**Comment by sonninnos** [comment]
Hmm, over here all mappers have that "---" option and here it does nothing..

There was a bug on this issue, but it was squashed ages ago. Sure you have a fresh version?

**Comment by Zombeaver** [comment]
I updated the core last night. When I scroll left or right through the mapper options for them just cycles through the entire list, but "---" isn't among the available values, and I tried adding the value manually to retroarch-core-options.cfg but it just sets it back to the default value after starting the core.

**Comment by sonninnos** [comment]
Odd. They should be nullable in Quick Menu -> Controls though. What platform are you on?

**Comment by rsn8887** [comment]
Did you actually update Retroarch or just the core? Do you get small print subtitles on the vice core options? We are using the new core option api, which was added to Retroarch just 2 months ago or so.

**Comment by rsn8887** [comment]
Do you see the `—-` (blank) among the options on all of the mapper entries or not. Press start on any of them to easily see them all.

**Comment by Zombeaver** [comment]
Ah, no I'm on an older version of Retroarch itself - 1.7.3. I'll try updating tonight and see if that fixes it.

This is what the entire list of options look like for me currently.

vice_Drive8Type = "1541"
vice_RetroJoy = "enabled"
vice_Controller = "joystick"
vice_mapper_y = "RETROK_LSHIFT"
vice_mapper_x = "RETROK_LSHIFT"
vice_mapper_b = "RETROK_SPACE"
vice_mapper_l = "RETROK_LSHIFT"
vice_mapper_r = "RETROK_LCTRL"
vice_mapper_l2 = "RETROK_KP_MULTIPLY"
vice_mapper_r2 = "RETROK_RETURN"
vice_mapper_l3 = "RETROK_n"
vice_mapper_r3 = "RETROK_y"
vice_mapper_start = "RETROK_ESCAPE"
vice_statusbar = "disabled"
vice_drive_true_emulation = "disabled"
vice_drive_sound_emulation = "disabled"
vice_drive_sound_volume = "10%"
vice_autostart_warp = "disabled"
vice_sid_model = "8580RD"
vice_resid_sampling = "Resampling"
vice_c64_model = "C64 PAL"
vice_border = "enabled"
vice_external_palette = "Pepto PAL"
vice_theme = "C64"
vice_reset = "Autostart"
vice_userport_joytype = "None"
vice_joyport = "Port 2"
vice_turbo_fire_button = "None"
vice_turbo_pulse = "2"
vice_mapper_select = "---"
vice_mapper_lu = "RETROK_LSHIFT"
vice_mapper_ld = "RETROK_LSHIFT"
vice_mapper_ll = "RETROK_LSHIFT"
vice_mapper_lr = "RETROK_LSHIFT"
vice_mapper_ru = "RETROK_LSHIFT"
vice_mapper_rd = "RETROK_LSHIFT"
vice_mapper_rl = "RETROK_LSHIFT"
vice_mapper_rr = "RETROK_LSHIFT"
vice_mapper_vkbd = "RETROK_F11"
vice_mapper_statusbar = "RETROK_F10"
vice_mapper_joyport_switch = "RETROK_KP_MULTIPLY"
vice_mapper_reset = "RETROK_END"
vice_mapper_warp_mode = "RETROK_PAGEDOWN"
vice_mapper_datasette_toggle_hotkeys = "---"
vice_datasette_hotkeys = "disabled"
vice_mapper_datasette_stop = "RETROK_DOWN"
vice_mapper_datasette_start = "RETROK_UP"
vice_mapper_datasette_forward = "RETROK_RIGHT"
vice_mapper_datasette_rewind = "RETROK_LEFT"
vice_mapper_datasette_reset = "---"

I create individual core option files (.opt) for many games so that things like the joystick port are already set to the correct value for the game, or true drive enabled if need be, so I've gone through and updated all my .opt files to the new format. Some things did change from the old version of the core to the new, like:

 vice_JoyPort = "port_ **>** vice_joyport = "Port

vice_DriveTrueEmulation **>** vice_drive_true_emulation

vice_SidModel **>** vice_sid_model

vice_ExternalPalette = "pepto-pal" **>** vice_external_palette = "Pepto PAL"

etc.

The above list is what mine looks like after converting the existing parameters over to the new format + adding in the new parameters, but that's on 1.7.3. I'll update to 1.7.7 tonight and see what happens.

**Comment by Zombeaver** [comment]
@sonninnos To clarify, yes the controls themselves are clearable in Quick Menu > Controls, and I guess that works too. I was referring specifically to the values in Quick Menu > Options:

![image](https://user-images.githubusercontent.com/24979172/62966384-ebe6d200-bdd4-11e9-8446-79feaee8ba01.png)

There's no way to blank these values out here that I can see (unless it's the result of being on 1.7.3).

**Comment by sonninnos** [comment]
I suspect the 1.7.3, because I can have multiple "---" no problem. It is always the first option when navigated inside that selection instead of doing left/right. (That navigation has some problems not related to this core).

**Comment by rsn8887** [comment]
> @sonninnos I'm on Windows. And to clarify, yes the controls themselves are clearable in Quick Menu > Controls, and I guess that works too. I was referring specifically to the values in Quick Menu > Options:
> 
> ![image](https://user-images.githubusercontent.com/24979172/62966384-ebe6d200-bdd4-11e9-8446-79feaee8ba01.png)
> 
> There's no way to blank these values out here that I can see (unless it's the result of being on 1.7.3). I basically just wanted to leave Quick Menu > Controls alone and then just clear out the stuff that I don't want it to mess with in Options.

Yes you are using age old Retroarch which doesn't support new core options API. So you are missing out on Option subtitles etc.

However, the core should display ALL the choices even on old Retroarch. This was a bug you found in the fallback code in the core. Thanks!

I fixed it here: https://github.com/libretro/vice-libretro/commit/f63d23e92682f9c39747dbd4042c5199b7e9fdda

It is still a bit weird on old Retroarchs because, with my fix, now the default option is always shown first, and replicated. E.g. the Disabled/ENabled options now show Disabled/DIsabled/Enabled, if disabled is the default, and Enabled/Disabled/Enabled, if enabled is the default, if you understand what I mean.

Since this stuff is only a fallback for people insisting to use old Retroarch versions, I think it is good enough.

I strongly urge to use latest Retroarch nightly, to get the new options API. You will also get little explanations under the options in small print, something the old API didn't support.

**Comment by Zombeaver** [comment]
I updated to 1.7.7 and can confirm that that has resolved this issue. Thanks again!
