### ISSUE TITLE
[Question] Android sound lag

### ISSUE THREAD

**Issue by MajorWilly** [libretro/vice-libretro#118]
Hi, just a question if anyone with Android can test for me. I seem to get quite a bit of audio lag. For instance, in this game -

https://csdb.dk/release/download.php?id=87211

When running, the sound of the guys feet hitting the ground seems to happen about 0.5 to 1 second later. I am currently using `ReSID` and sampling `Fast`. I also tried `FastSID` but got the same result. The Vice statusbar tells me 50fps and RetroArch also says 50fps. Just wondered if you could try this and see if it's a thing on Android or just my device.

I tried the Windows version of lr-vice and it's perfect.

**Comment by sonninnos** [comment]
This is very handy for testing: [delaytest.prg](http://pihaus.org/random/delaytest.prg)

**Comment by MajorWilly** [comment]
I tried that tool. It's hard to tell, but the sound happens slightly after the screen changes colour. If anyone can confirm any lag on Android with this tool and the game I linked above (it's a lot more noticeable with the game).

**Comment by rsn8887** [comment]
Try Settings->Latency->Audio Latency and reduce that setting to something small like 20 ms. On my Android device (NVIDIA Shield Portable), for some reason the default was 128 ms, which is way too high and causes terrible audio lag.

I did some extensive testing on Nintendo Switch and verified on that platform that the Vice core has exactly the audio lag that agrees with the latency setting. I tested by filming the output using a slomo camera and counting frames between video and audio.

But whether the latency setting is honored or not depends on the audio driver.

Historically, Android has always had terrible audio lag. I am not sure when that was improved, but my NVIDIA Shield Portable definitely shows larger audio lag than the latency setting displays, on all cores.

**Comment by MajorWilly** [comment]
Thanks for the info, I didn't know that. I'm on Android 4.4.4 so looks like i'm stuck with it !

While i'm here, regarding Autostart Warp. It doesn't make any difference (probably my device again). I timed the speed of loading and it seemed the same time on or off. In the statusbar it says 5W, so is that 5fps ?

**Comment by rsn8887** [comment]
Autostart warp makes a difference if you turn vsync off in Retroarch->Video settings, otherwise the warp speed is limited by vsync to 50 fps.

**Comment by rsn8887** [comment]
You might be able to update your device to more modern Android, and the audio lag might become better? It is a risk though all kinds of things could break. That's why I never updated my Shield Portable. I am stuck with 4.2.0 and horrible audio lag.

**Comment by MajorWilly** [comment]
Yeah, I think i'll turn off Autostart Warp and just use RetroArch FastForward which is 100% faster. Thanks for your help.
