### ISSUE TITLE
[PS3] [enhancement] Build vice-cores for Playstation 3.

### ISSUE THREAD

**Issue by Electrolyt** [libretro/vice-libretro#124]
In an earlier build like version 1.7.1 where a commodore c64 core released, but this was still buggy.
Is it possible to build the new vice-cores for the playstation 3 within the nightlies ?

**Comment by sonninnos** [comment]
Probably this is the wrong place to ask this, because the makefile does have PS3 added as a platform, but apparently the buildbot just does not build it. I can't test if it even works, and I also don't know who to contact about it.

**Comment by sonninnos** [comment]
I guess this can be closed here and/or moved somewhere else.
