### ISSUE TITLE
Vice64x fails to autoload zipped .d64 images

### ISSUE THREAD

**Issue by RoofTop1** [libretro/vice-libretro#136]
**_Description:_**
Fails to autload file from a zipped d64 image with True Drive emulation on.

Why woulde I need to have TDE turned on you say ??  Well, some games 
requires TDE to be on to be able to load files from disk.

**_Expected behavior:_**
To load directory track 18 and search file name, then go to actual track for file and load it. End
with a ready prompt and run the file with "run".

**_Actual behavior_**
Tries to load directory track 18 to search for file, then bumps to track 1 and retries
track 18. Then ends with a file not found. As if no disk was inserted.

**_Steps to reproduce the bug_**
Create a option file for any zipped .d64 game.
In the option file ENABLE True Drive Emulation.
Now start and run the zipped file.  And watch that it fails to load.

**_Vice Version:_**
1.7.8 - Vice x64 3.3 117d1e133

**_Environment information:_**
Retroarch for Playstation Classic.

**_Last minute note:_**
Please note that loading zipped .T64, .CRT and .PRG files works fine.
Also notice that loading zipped .D64 with true drive emulaton turned off also works fine.

**Comment by sonninnos** [comment]
Hmm, RetroArch is supposed to unzip the zip in temp and present the unzipped file to the core. At least that is what happens here with Windows.

I can't test any further until I find a way to prevent RA from doing the unzipping.

**Comment by rsn8887** [comment]
What is this version 117d1e1 you are using?

Can you use try the latest core version f3e7249?

**Comment by RoofTop1** [comment]
I download the latest cores for Playstation classic from https://classicmodscloud.com/classic_libretro/stable/classic_armv8_a35/

**Comment by rsn8887** [comment]
Somehow that buildbot is not using the master branch, but some temporary PR branch to build.

So you are not using the latest core version, but some hacked thing. Until the PS Classic maintainers get their buildbot in order to actually build from latest master branch, there's not much I can do, I think.

**Comment by rsn8887** [comment]
I did a bit more digging, and the PlayStation Classic core seems to be build from this repo https://github.com/Classicmods/vice-libretro

So maybe you can open an issue there. I don’t know who is the maintainer of that repo. Maybe @evilwraith , since he once made a PR from that repo.

**Comment by evilwraith** [comment]
That's really strange. I'll check it out but the build on our site should only be a few days old, at most.

**Comment by sonninnos** [comment]
Even standalone SDLVICE behaves rather oddly if launched with a zipped d64 or if autostarting a zipped d64 from the menu while running. The whole application just minimizes when it unzips the zip to temp..

Perhaps it is best to figure out why that Classic does not extract the zip and instead offers it directly to the core. Like it just forces `info->block_extract` to true in `retro_get_system_info`.
