### ISSUE TITLE
Some .tap file won't load

### ISSUE THREAD

**Issue by 0100101000101** [libretro/vice-libretro#138]
Some cassette .tap files from old magazines won't load
![IMG_20190927_154532](https://user-images.githubusercontent.com/42087209/65774106-ec95b680-e13d-11e9-87a1-397a421ff8a0.jpg)

**Comment by sonninnos** [comment]
Please first confirm that they work in standalone VICE.

**Comment by 0100101000101** [comment]
Works with run+return.
Close this issue, thank you.
