### ISSUE TITLE
Using cartridges via vicerc no longer work

### ISSUE THREAD

**Issue by sonninnos** [libretro/vice-libretro#140]
Thanks @monkeyman79 for the updates, but I stumbled upon a breakage and can't seem to figure out how to it fix easily and not break something else.

I've been attaching an Action Replay cartridge via `vicerc` in system/vice/ like so:

> [C64SC]
CartridgeFile="path"

But it does nothing anymore. I've narrowed it down to two culprits in `retro_run()`:
`resources_set_defaults()` AND `initcmdline_restart()` (specifically `mon_cart_cmd.cartridge_detach_image`)

Perhaps you have the quickest understanding of what needs to be done. Please also wrap the new `initcmdline_restart()` function with `#ifdef __LIBRETRO__` so it will make future source updates a lot less painful. Thanks in advance!

**Comment by monkeyman79** [comment]
You are right, the `cartridge_detach_image` and possibly other `xxx_detach` functions should be called earlier - before `resources_set_default` and `resources_load`. I'll fix that later today.

**Comment by rsn8887** [comment]
I merged PR #141 too early. Please open a new PR @monkeyman79 , thanks!

**Comment by monkeyman79** [comment]
@sonninnos Btw. do you have any trick to make Action Replay go directly to fastload after boot?

**Comment by sonninnos** [comment]
> @sonninnos Btw. do you have any trick to make Action Replay go directly to fastload after boot?

Only by using MK4, since it has no menu.
