### ISSUE TITLE
Change necessary for cores to work on iOS

### ISSUE THREAD

**Issue by jet082** [libretro/vice-libretro#146]
The various cores compile alright, but they do not actually work. The fix to get them working is quite simple.

In ``vice/src/arch/libretro/uistatusbar.c`` change ``static char str[3];`` in ``char* joystick_value_human(char val)`` to ``static char str[6];``

Then the cores will work fine.

**Comment by rsn8887** [comment]
Fixed in 23185a6734ca97f55cedafba4536df15094dd2c6

**Comment by sonninnos** [comment]
Isn't 4 enough?

**Comment by rsn8887** [comment]
I just thought of that, but since the original post requested 6, I put six. Two bytes extra shouldn't hurt anyone :)
