### ISSUE TITLE
Netplay on Retroarch?

### ISSUE THREAD

**Issue by Anths2016** [libretro/vice-libretro#147]
Why Vice on Retroarch don't support netplay? I hope you can add this important feature!

**Comment by rsn8887** [comment]
What system? What is the error? It should just work now that savestates are done without temp files.

**Comment by Anths2016** [comment]
The system is Windows. I can't view my name in the room of the hosts, so I imagine that netplay does not work.

**Comment by sonninnos** [comment]
Maybe those serialization quirks play a role?

**Comment by sonninnos** [comment]
Not worth the hassle since Parsec exists, thus I'll close this.
