### ISSUE TITLE
Error on cloning

### ISSUE THREAD

**Issue by Roughtrade** [libretro/vice-libretro#158]
remote: Enumerating objects: 8437, done.
remote: Counting objects: 100% (8437/8437), done.
remote: Compressing objects: 100% (6174/6174), done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: zu frühes Dateiende
fatal: index-pack fehlgeschlagen

**Comment by sonninnos** [comment]
Hardly the core's fault. Works fine here:

```
# git clone https://github.com/libretro/vice-libretro.git
Cloning into 'vice-libretro'...
remote: Enumerating objects: 286, done.
remote: Counting objects: 100% (286/286), done.
remote: Compressing objects: 100% (185/185), done.
remote: Total 250138 (delta 195), reused 157 (delta 101), pack-reused 249852
Receiving objects: 100% (250138/250138), 220.85 MiB | 26.62 MiB/s, done.
Resolving deltas: 100% (212104/212104), done.
Updating files: 100% (8469/8469), done.
```

**Comment by rsn8887** [comment]
This is a problem you have to fix with your it installation or network on your end.
