### ISSUE TITLE
"Virtual Device Traps" option not present

### ISSUE THREAD

**Issue by lodgerz** [libretro/vice-libretro#16]
hi,
can you add "Virtual Device Traps" option to gui settings? without it isn't possible to play with "True Drive Emulation" disabled (when load a game it always says "DEVICE NOT PRESENT ERROR"). Need to add "VirtualDevices=1" on vicerc.
Thanks.

**Comment by lodgerz** [comment]
i have read you have add "VirtualDevices toggle". Thanks, but i can't see virtualdevices option on quick menu of retroarch.

**Comment by r-type** [comment]
hum turn off TDE core option should enable VirtualDevices (at least it works for me on linux64).

Btw you could try this one
https://filebin.net/asxpjh57876wpq0y

**Comment by lodgerz** [comment]
i have tried your core but it doesn't work:
```
$ retroarch /usr/lib/libretro/x64sdl_libretro.so giana\ sisters.prg --verbose
[INFO] Redirecting save file to "/usr/lib/libretro/x64sdl_libretro.srm".
[INFO] Redirecting savestate to "/usr/lib/libretro/x64sdl_libretro.state".
[INFO] === Build =======================================
Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 
Built: Dec 31 2017
[INFO] Version: 1.7.0
[INFO] =================================================
[INFO] [Config]: Loading default config.
[INFO] [Config]: loading config from: (null).
[INFO] Looking for config in: "/home/lodger/.config/retroarch/retroarch.cfg".
[ERROR] RetroArch is built for dynamic libretro cores, but libretro_path is not set. Cannot continue.
[ERROR] Fatal error received in: "init_libretro_sym()"
[ERROR] This core requires a content file.

```

i use ArchLinux 64bit with Linux 4.14.15-1-ARCH

**Comment by r-type** [comment]
no you should hit F12 to get the same menu like upstream. inside you can setup your vice like usual vice 3.1

**Comment by lodgerz** [comment]
oh, i didn't know. unfortunately menu is unusable: when i press a direction it goes forward of 2 lines instead of 1.
Are you the creator of this version? where is the source?

**Comment by r-type** [comment]
yes you have to use joypad for menu.

sources are here for vice http://sourceforge.net/projects/vice-emu/files/releases/vice-3.1.tar.gz/download and here for sdl-libretro https://github.com/libretro/sdl-libretro.

also for saving and have all the file (keymap,pal ect) , you have to put the data folder found in vice-3.1.tar.gz in your retroarch system directory. 
then when you will save settings from menu it will create the sdl-vicerc in RA-sytemdir/data/.vice/

**Comment by rsn8887** [comment]
This was fixed a long time ago. Setting true drive emulation on or off correctly enables/disables virtual device.
