### ISSUE TITLE
Fails to load

### ISSUE THREAD

**Issue by Solo187** [libretro/vice-libretro#160]
Strange issue with latest version of the core  on the nvidia shield. When storing games on external hd in the nvidia_shield folder, some games will load but the majority wont. Retroarch just crashes. When i put the same games on internal, they work fine. Very odd. All was fine until recently.

Edit: just to add, this happens with all of the vice cores not just c64. No other cores have this issue

**Comment by sonninnos** [comment]
Please show logs of some sort, otherwise it is quite impossible to go on. No related changes has been made lately. Talking about disk images and in which formats? Can you test and find a version where this does not happen?

**Comment by Solo187** [comment]
I can see I'm not going to be a great deal of help here as im using the android version im not sure how to get your logs. Also i cannot do any core regression as my shield isn't rooted so I can't access the core folder. Unless you have an alternative url i could use to directly download older core versions into retroarch. On further testing, the plot thickens as it appears that if i zip the file & then run it, the games will start. The file is extracted to the retroarch temp folder which is on the same external hd & it has no trouble starting from there. The filetypes are d64 & tap. Crt images seem to have no trouble? All the files are stored in the same directory structure with separate folders e.g Carts, Tapes, Disks

**Comment by sonninnos** [comment]
I have no idea how could anything in the core itself affect that kind of thing.. Are you sure nothing else has changed on your system, like available space and/or file/directory permissions..?

How long ago did it work and when did you update the core?

**Comment by Solo187** [comment]
I've no idea whats going on either. Its really strange. My first thought was some kind of permissions too, but nothing at all has changed with my setup. Also the same files work perfectly in other emulators. I just really like these vice cores & retroarch. The ability to add overlays etc. I have it all setup in arc browser & up until this past week it was all working flawlessly. The only thing I've done is update the core, as i do pretty much daily for all of them. I've upped a screen capture to show you exactly what's happening https://drive.google.com/file/d/1Vc2mI-Fg6WC2fG2ENGFDyq_cX-vpEp42/view?usp=drivesdk

**Comment by sonninnos** [comment]
One thing just dawned to me, I'll try to investigate deeper as soon as possible. I just recently added a feature that shows the attached image on the statusbar for a moment if it is a disk or a tape, for helping out M3U juggling. 

A few examples of the offending filenames and filepaths could help also. I assume the filenames stay intact while zipped, so most likely there is something unexpected in the full path that it screws up the parsing.

**Comment by Solo187** [comment]
Awesome, Well seems like we've narrowed it down then. Hopefully that's it

**Comment by sonninnos** [comment]
Got it crashing on Windows too with very long paths, so hopefully it no longer does it on any platform.
