### ISSUE TITLE
Maximum Zoom mode crash

### ISSUE THREAD

**Issue by MajorWilly** [libretro/vice-libretro#172]
Hi, I couldn't get the zoom Hotkey to work. I tried setting it as F12 and mapped to my L2 button but it didn't want to do anything.

I tried changing the zoom mode manually but it crashed on Maximum.

This was on Vice x64 fast on Android. Haven't tried Windows yet as I don't know if the buildbot is ready for it.

Lastly, what does the VIC sound leak option actually do ? I couldn't find any information on it.

Edit: I just tried the accurate build (Android) and it slows to a crawl when entering and exiting the Retroarch menu. It never used to be this slow. Also crashes when manually selecting Maximum zoom.

**Comment by sonninnos** [comment]
The zoom hotkey only toggles it off/on, so it needs to be set first.

What is the screen resolution of the device? The maximum setting is the only setting that does very little horizontal cropping to fit a 16:9 screen properly. Always forced on landscape I presume?

The audio leak should be very familiar if you ever owned a C64. It does all the buzzing sounds depending on the colors on the screen. It could use some volume control though, since you need headphones to hear it.

What, even the menu while paused is slow?

**Comment by MajorWilly** [comment]
Sorry, the zoom hotkey does work. I was expecting it to cycle through small,medium,large etc. I forgot you changed it.

My Android device screen is 1280x720 (Landscape locked). Setting the zoom to Maximum crashes when exiting the menu (or booting into a game).

**Comment by MajorWilly** [comment]
@rsn8887 Could you confirm this on your Android Shield device as I think it has the same resolution.

Zoom maximum setting crashing (fast and accurate builds)
Sluggishness after opening and resuming from Retroarch menu the first time (accurate build)

**Comment by MajorWilly** [comment]
This maybe a global thing. I just tried the Windows version and both issues happen there too.

**Comment by sonninnos** [comment]
I tried dropping to 720p too, but it made no difference on either core.

Could you post the log and/or opt file?

**Comment by MajorWilly** [comment]
I'll type this as it happens ! Some progress. I renamed the Core Options file so it generated a new one. So with all default options I got no sluggishness after opening and closing the Retroarch menu (accurate core). It still crashes when setting Maximum zoom though.

**Comment by sonninnos** [comment]
If I change RA's video_driver to "gl", I get instant crash on startup if zoom is at max. I use "vulkan" normally, but "glcore" works ok too.

**Comment by MajorWilly** [comment]
My video driver is set to "gl" (always has been). At the moment though, it's not crashing !!

**Comment by MajorWilly** [comment]
So final conclusion. I think it's all related to Autostart Warp. If I turn off Autostart warp then Maximum zoom works. If I turn warp off it crashes when zoomed Maximum ?!?

**Comment by sonninnos** [comment]
Try using the warp hotkey manually too if it does the same, as it most likely should. But how the warp and the zoom are related in any meaningful way is a mystery.

**Comment by MajorWilly** [comment]
My device only lists 'gl' and 'vulkan'. I just left it on the default 'gl'. I keep having trouble trying to reproduce this. I'm going to write down the steps.

**Comment by MajorWilly** [comment]
Start with
Autostart Warp OFF
Zoom OFF

Game loads OK. Change to
Zoom Maximum
I then closed content and reloaded game. Crashed.

If I change to
Autostart Warp ON
Zoom Maximum works fine but if I goto the Retroarch menu and return I get the sluggishness.

**Comment by MajorWilly** [comment]
[retroarch__2019_12_09__18_41_37.log](https://github.com/libretro/vice-libretro/files/3941213/retroarch__2019_12_09__18_41_37.log)

**Comment by MajorWilly** [comment]
Are you having any luck finding the reason for these issues ? As I said, it also happens on Windows. The severe slowdown with Autostart Warp ON when entering/exiting the menu at the beginning of loading and the Maximum zoom crash. Personally I think toggling between Medium and Off is the best anyway.

My Windows laptop uses the 'gl' video driver also. 'vulkan' crashes Retroarch for me.

**Comment by sonninnos** [comment]
I have no idea how the vsync skipping Warp fix works since I did not do it. Try asking about it here: https://github.com/libretro/vice-libretro/pull/154

Also have no idea why on "gl" the max zoom crashes. Are you sure you can't use even "glcore"?

**Comment by MajorWilly** [comment]
'glcore' seems to crash Retroarch on my Laptop as well and it's not available on my Android device. It's not really a problem for me as I think Medium Zoom looks the best and for people that wan't Maximum zoom, they may as well just Disable Borders ! I just thought i'd point out that there was a crash in there. As for the severe slowdown with Autostart Warp on, have you experienced it ? Just go in and out of the Retroarch menu at the beginning of loading.

**Comment by sonninnos** [comment]
Yes, I can crash it too only when using "gl". And yep, seems to be something weird with the Warp even without zooms and even with vulkan. It sure loads faster like it should, but it also locks up the whole RA.

**Comment by MajorWilly** [comment]
Thanks for confirming, i'm glad it's not just me ! Just hope these sample rate updates don't start effecting Retroarch as well.

**Comment by MajorWilly** [comment]
There maybe something wrong with the Windows 32-bit version. It hasn't built for a couple of days. There's still no Zoom option or Audio Leak Emulation etc.

**Comment by sonninnos** [comment]
I don't see any errors in buildbot logs, and the date in the files seems to be this day: http://buildbot.libretro.com/nightly/windows/x86/latest/

**Comment by MajorWilly** [comment]
Lol, it's literally just updated !! Right after I updated the cores. Why did it take 2 days ?

**Comment by sonninnos** [comment]
For some reason I can't make it crash on "gl" anymore.

Last time I tried when it did crash, I noticed it did not crash if I held any key down while starting up.. Does not compute.

Any difference there?

**Comment by MajorWilly** [comment]
Still crashes for me (Windows & Android). The weird thing is, sometimes it does work. If I leave the core option set to Maximum, sometimes it works but mostly Retroarch crashes about 4 or 5 times before the game will load. Lately i've just been leaving it on 'Medium' as I prefer to see a little bit of the border at the top and bottom so I can see if the game is using the border for graphics, then I toggle the border off. Is there much need for the 'Maximum' option anyway ?

I'm also still getting the odd random crash when running a game on the fast version (Windows). Not related to the border as it does it when set to other zoom levels/off.

**Comment by AnaLogiC76** [comment]
As the autostart-warp-issue caused general startup instability and should be fixed now, does this issue here still happen?

**Comment by MajorWilly** [comment]
Yes, the Maximum Zoom mode still crashes (sometimes works), so probably not related to the Autostart Warp. Apparently it only happens with the 'gl' video driver as sonninnos has experienced it also. Personally, I leave mine set on Medium now as it looks the best and just toggle it off for overscan games.

**Comment by MajorWilly** [comment]
This maybe related to the 32-bit version ? I just updated Retroarch to the 64-bit version and am now using 64-bit cores. I can't get it to crash ! It still crashes on Android (which mine is 32-bit).

**Comment by sonninnos** [comment]
I started having these randomly here too for who-knows-what-reason after updating RA, maybe, but so far looks like I found another way to achieve the same result. I'll test some more before I lay my spells upon thee.
