### ISSUE TITLE
Severe slowdown if using menu during Autostart Warp

### ISSUE THREAD

**Issue by MajorWilly** [libretro/vice-libretro#174]
If you enter and exit the Retroarch menu during the Autostart Warp sequence then you get some serious slowdown and sometimes lock-ups.

**Comment by AnaLogiC76** [comment]
I've found that for the first few rendered frames after emulator-start timing is not stable and this will cause warp-mode to skip too many frames and framerate will go down seriously, this would explain the sluggish behaviour.
Fixed in PR #180 and I hope this fixes your case aswell.

**Comment by MajorWilly** [comment]
This seems to be fixed now but there is still another related issue https://github.com/libretro/vice-libretro/issues/179
