### ISSUE TITLE
x64scpu does not work

### ISSUE THREAD

**Issue by Tuxie** [libretro/vice-libretro#178]
I know that you are already fully aware about this but I still want to track it so I created this issue.

The x64scpu core does not compile. Since there are almost no `#if defined(__XSCPU64__)` in the code compared to the other emutypes, I guess that the work on supporting it has not really started yet.

I am really looking forward to being able to play Metal Dust in RetroArch on my Shield TV.
https://www.protovision.games/shop/product_info.php?products_id=133

**Comment by sonninnos** [comment]
I can get it to compile and run, but there is just no output.

**Comment by sonninnos** [comment]
Good news: Metal Dust is working fine now.
