### ISSUE TITLE
Random crashes when starting games - Windows fast version (Autostart Warp related)

### ISSUE THREAD

**Issue by MajorWilly** [libretro/vice-libretro#179]
I'm still getting random crashes when trying to start games using the (Windows) fast version. The accurate build seems OK. Log attached if it's of any use.

[retroarch__2019_12_18__12_52_54.log](https://github.com/libretro/vice-libretro/files/3978488/retroarch__2019_12_18__12_52_54.log)

**Comment by rsn8887** [comment]
Which version worked? Or was this always a problem?

**Comment by MajorWilly** [comment]
It's been a problem for a while. It used to work OK but I don't know which version the problem appeared. Buildbot doesn't have previous versions for Windows.

**Comment by MajorWilly** [comment]
I think this problem could also be related to the Autostart Warp. I just turned it off and haven't had any crashes. I'll have to wait to check the new fix just submitted for the Autostart Warp https://github.com/libretro/vice-libretro/pull/180

**Comment by MajorWilly** [comment]
Still a lot of random crashes on aa8f830 . If you turn OFF Autostart Warp it doesn't crash.

**Comment by AnaLogiC76** [comment]
As little sense as this makes, I actually can confirm this!
I had never run x64 here, only x64sc, so conveniently all core-options are at default, just enabled autostart warp, tried autostarting a d64 and 4 out of 5 times RA crashes without even a single frame being rendered.
At this point a remark, x64 has been replaced by x64sc for quite a while as the performance difference is nowadays considered to be no longer relevant so I would really recommend to switch - are there performance reasons on your system not to do so?
But still x64 shouldn't crash that way.
I'll have a look, with hopes not that high, if I can see anything.

**Comment by AnaLogiC76** [comment]
That was unexpected, hope I got that one with PR #181.
Turns out x64 is so fast it can render a frame within less than a nanosecond, then we would measure a frame-time of 0 and divide by that, which crashes anything using standard mathematics.
Hope with that fix you can now enjoy autostarting with fast warp.

**Comment by rsn8887** [comment]
x64 is the only choice on Vita that is not horrendously slow btw.

**Comment by AnaLogiC76** [comment]
Seems plausible to me now that I've seen while debugging that frame-times for x64 are routinely a third of what they are with x64sc, a three-fold speed increase certainly is not irrelevant.
This answers my un-asked question if there is still a need for x64.

**Comment by MajorWilly** [comment]
Yeah, I haven't found a reason to use x64sc. Everything I've tried has always worked on the fast version except one demo which had very slight glitches. The demo is called surprisingly, 'Cycle' !
