### ISSUE TITLE
.crt cartridge loading non-working on Wii U platform

### ISSUE THREAD

**Issue by vaguerant** [libretro/vice-libretro#191]
I'm unable to run any software in `.crt` format at all on the Wii U. This includes No-Intro verified cartridge dumps and freeware homebrew such as Sarah Jane Avory's Neutron. I have confirmed the exact same files run without issue on RetroArch for Android. Looking through the RetroArch logs, the relevant part seems to be here:
```
[libretro INFO] Autodetecting image type of `sd:/Game Backups/Commodore 64/Neutron.crt'.
[libretro ERROR] Import GCR: Unknown GCR image version 82.
[libretro INFO] Unknown disk image `sd:/Game Backups/Commodore 64/Neutron.crt'.
[libretro ERROR] Cannot open file `sd:/Game Backups/Commodore 64/Neutron.crt'
[libretro INFO] CART: 'sd://sd:/Game Backups/Commodore 64/Neutron.crt' is not a valid CRT file.
[libretro INFO] Loading PRG file `sd:/Game Backups/Commodore 64/Neutron.crt' with direct RAM injection.
[libretro INFO] Resetting the machine to autostart '*'
[libretro INFO] Opened device `retro', speed 48000Hz, fragment size 0.7ms, buffer size 0ms
[libretro INFO] Turning Warp mode on
[libretro INFO] `sd:/Game Backups/Commodore 64/Neutron.crt' recognized as program/p00 file.
```
Drilling down a bit further:
`[libretro INFO] CART: 'sd://sd:/Game Backups/Commodore 64/Neutron.crt' is not a valid CRT file.`
Not sure what the deal is with `sd://sd:/`, that's a bit weird. Possibly this is a simple path issue with the double-prefix. But if it's a more serious file heuristics issue then, I don't know, maybe endianness issues could be causing the file to be misread as not matching expected `.crt` format values?

I don't know anything about compiling for Wii U, but I'm happy to run any test builds as provided.

**EDIT:** Just to confirm, several other formats load without issue, including `.tap`, `.d64` and `.g64`. These and `.crt` are currently the only formats I've tested on my end.

**Comment by sonninnos** [comment]
@rsn8887 

Shouldn't this be fixed with just adding `WIIU` to the `__SWITCH__` header guard in `src/arch/libretro/archdep.c` at line 399?

```
int archdep_path_is_relative(const char *path)
{
#ifdef __WIN32__
  return !((isalpha(path[0]) && path[1] == ':') || path[0] == '/' || path[0] == '\\');
#elif defined(VITA)
    if (path == NULL)
        return 0;
    if (*path == '/')
        return 0;
    // Vita might also use "ux0:" or "uma0:" for absolute paths
    for (int i = 0; i <= 4; i++)
    {
        if (path[i] == '\0')
          return 1;
        if (path[i] == ':')
          return 0;
    }
    return 1;
#elif defined(__SWITCH__)
    if (path == NULL)
        return 0;
    if (*path == '/')
        return 0;
    // Switch might also use "sdmc:" for absolute paths
    for (int i = 0; i <= 4; i++)
    {
        if (path[i] == '\0')
          return 1;
        if (path[i] == ':')
          return 0;
    }
    return 1;
#else
    if (path == NULL)
        return 0;
    return *path != '/';
#endif
}
```

`archdep_path_is_relative()` is run in `cartridge_attach_image()` found in `src/c64/cart/c64cart.c`

**Comment by rsn8887** [comment]
Not sure but worth a try

**Comment by sonninnos** [comment]
Please update the core and report if it worked or not.

**Comment by vaguerant** [comment]
Buildbot is still serving yesterday's build right now, but will do as soon as I'm able to.
