### ISSUE TITLE
Corrupted text on Retroarch 1.8.2 widgets 

### ISSUE THREAD

**Issue by DarishZone** [libretro/vice-libretro#194]
I'm afraid retroarch changed something on widgets - which are messages text - and some cores have not been updated, just guessing.
Basically text on lr-Vice core (lr-Px68k is also affected) is messed, you can see/reproduce just when emulator start and controller are recognized, or when you save state. Previous version of lr-vice 3.3 is not affected, curiously.

**Comment by DarishZone** [comment]
Tested on
Retropie and Batocera, platform: Rpi

**Comment by jdgleaver** [comment]
It turns out that this was a frontend issue - it should be fixed in the retroarch nightlies once this gets merged: https://github.com/libretro/RetroArch/pull/10246

**Comment by Darknior** [comment]
Excellent thanks a lot :)

**Comment by jdgleaver** [comment]
You are very welcome!

We're cleaning up a bunch of threaded video stuff at the moment, and this issue was very helpful for debugging purposes (never would have found the problem, otherwise)  :)

**Comment by DarishZone** [comment]
I confirm issue is fixed now, thanks very much.
