### ISSUE TITLE
Non-working defaults

### ISSUE THREAD

**Issue by escalade** [libretro/vice-libretro#2]
Tape drive and joystick does not work by default. Specifically, drive 8 type needs to be set to 1541 and true drive emulation needs to be turned on. Retro joypad0 needs to be activated in the options as well for joystick to work.

I understand that you can use a full vicerc but to be a useful RA core it should be plug & play for noobs ;)

**Comment by r-type** [comment]
I will look at this when i have time.

**Comment by r-type** [comment]
so i generated the 94 embedded files , vice load fine with.
but one big problem remain. it miss the keyboard default keymap (that are not embedded).

Keyboard: Error - Default keymap not found, this should be fixed. Going on anyway... 
then kbd input are not working until you provide sdl_sym.vkm in data\C64

**Comment by r-type** [comment]
by default 1541 DRIVE / TDE ON /  RETROJOY ON.
