### ISSUE TITLE
change aspect ratio?

### ISSUE THREAD

**Issue by trioan** [libretro/vice-libretro#202]
Hi, is there an option to switch between 4:3 (current DAR) and NTSC / PAL based on pixel aspect ratios?
http://hitmen.c02.at/temp/palstuff/

**Comment by sonninnos** [comment]
Not on the core, but on the frontend. Why should the core offer it?

**Comment by trioan** [comment]
Other emulators like Genesis Plus GX, Mesen, Mesen-S, Nestopia, Snes9x et al offer in the core. So thought it was normal.
