### ISSUE TITLE
"no core options available" in "options" menu (lr-vice version 1.7.6, retropie pi 3B)

### ISSUE THREAD

**Issue by soge73** [libretro/vice-libretro#206]
Hello,

I haven't got any content in the "options" folder in retroarch, just a "no core options available" message. I tried updating from source with no effect. 
This after a fresh install of retropie on a new card. ( As such the games launch but with no sound).

I hope my request isn't out of place, I just can't seem to find any information about this anywhere...  Many thanks anyway!

**Comment by rsn8887** [comment]
You are using a completely outdated version of Retroarch. You have to update Retroarch, too, not just the vice core. The current stable version is 1.8.4.

**Comment by soge73** [comment]
Thanks for your quick reply,

I tried to update retroarch through the retropie menu, updated from source, still the same version.
Tried through the online updater within retroarch (after enabling it), nothing happened when i tried to update the core, so I updated what I could within the online updater menu (assets, etc)... 
bad idea, now I can't access the retroarch menu with the hotkey combination; I configured my controller again with "configure input" in emulation station but still can't access retroarch...

Sorry for being such a newbie, hope you can help a little further!

**Comment by soge73** [comment]
(actually I can't enter retroarch or start a game at all on any system, I suppose I need to delete something... but am at a loss!)

**Comment by rsn8887** [comment]
The Retropie source code seems to indicate that a RetroPie update should install Retroarch version 1.8.4. (https://github.com/RetroPie/RetroPie-Setup/blob/7eff06b464c63c2080f9aa02ac5c01f6067f07d8/scriptmodules/emulators/retroarch.sh#L42)

The problem you have with updating is a Retropie issue, not a core issue. Please ask for help in the official Retropie forum: https://retropie.org.uk/forum/

Good luck!

**Comment by soge73** [comment]
Just did. Thanks!

**Comment by sonninnos** [comment]
Is this issue still valid?

**Comment by cmitu** [comment]
It's not - solved in https://retropie.org.uk/forum/topic/25070/, user messed up their configuration by playing with `root` and breaking file permissions.

**Comment by sonninnos** [comment]
Nice one, thanks for letting us know!
