### ISSUE TITLE
VSF snapshots saved using WinVICE and GTK3VICE don't load

### ISSUE THREAD

**Issue by bc-bytes** [libretro/vice-libretro#213]
As per title. Not sure if this is a bug, or a feature not yet implemented. Would be super-useful to have support for this, so we can load snapshots that bypass trainers.

**Comment by sonninnos** [comment]
Hard to say. This core uses the exact same savestate files as the standalone, so there should not be any reason why it wouldn't work, except if there is a version check or something.

Wouldn't it be far easier to just make your own post-trainer savestate with the core, instead of all the renaming etc..?

**Comment by bc-bytes** [comment]
Yes, you're right, it is easier that way. I didn't realise that the .state files could be loaded directly by the core. I did notice though that save states tend to have this weird sound that occurs the moment you load a state. Is that a bug, or something that was common on the C64? It sounds like an audio routine is initialising, or similar.

**Comment by sonninnos** [comment]
Does it stay on and does it occur on all different SID models and/or options and does it sound the same on all games?

I've also noticed some odd extra sound while rewinding, but nothing major.

If standalone VICE doesn't do the same, then it is the core's fault.

**Comment by bc-bytes** [comment]
It's like a very quick double-click sound. Not tried on different sound chips. It also happens on the Windows version of VICE.

**Comment by sonninnos** [comment]
Oh cool, VSF files saved with SDLVICE actually do launch fine. I'll add the extension to the supported list.
