### ISSUE TITLE
Add RA support and memory maps

### ISSUE THREAD

**Issue by salvadorc17** [libretro/vice-libretro#214]
I have some progress made in standalone emulator for this system. Can you enable memory maps for it, I have hooked memory in c64mem.c method Mempowerup.

For Rom loading i have hashed full rom data into uilib.c using loaded rom data.

**Comment by sonninnos** [comment]
Care to explain what would that actually mean and accomplish..?

**Comment by salvadorc17** [comment]
Retroachievements support loading memory maps, from libretro

**Comment by sonninnos** [comment]
I have no idea how to get this ball rolling. `retro_get_memory_data` seems to already have access to the memory, and I can't find any useful info on what needs to be done to the core to get it working, just tutorials on setting the client side up.

Of course it needs `RETRO_ENVIRONMENT_SET_SUPPORT_ACHIEVEMENTS` to be set, but what else? And how to confirm that it actually does what it is supposed to?

**Comment by salvadorc17** [comment]
i have made same in vice emulator, if youre asking where to get that you need to capture memory from x64 in class  c64mem.c method Mempowerup.

**Comment by sonninnos** [comment]
Okay, that first one is already covered. I'll add the environment on the next PR (not the current one) if someone else does not beat me to it.

**Comment by salvadorc17** [comment]
Maybe dont close this still, testing with Ralib emulator i get issue from the retro_set_controller_port_device callback, wonder why it happen.

**Comment by sonninnos** [comment]
Sounds like that is the job for RALib to figure out.. as in I don't think anything could or should be done differently in the core, but of course it will be fixed at once if it is something out of specs that causes the problems.

**Comment by salvadorc17** [comment]
It should be because Ralib works with the vice core dated October 2019, not sure what you added after it, that make it crashes into emulator

**Comment by salvadorc17** [comment]
[ERROR] [COR] Unimplemented env call: 52 (52)
[ERROR] [COR] Unimplemented env call: 57 (57)

**Comment by sonninnos** [comment]
ENV 52 = `RETRO_ENVIRONMENT_GET_CORE_OPTIONS_VERSION`
ENV 57 = `RETRO_ENVIRONMENT_GET_DISK_CONTROL_INTERFACE_VERSION`

Those are not going anywhere, so it is RALibs problem if they are not supported.
