### ISSUE TITLE
Windowed mode initial size bug?

### ISSUE THREAD

**Issue by trioan** [libretro/vice-libretro#221]
Thanks for the new GUI and options that came with it. 👍 

I think this is a bug but unsure. When I launch a game (soulless) in RA window mode x1 scale, window size seems to be wrong sometimes. No zoom.

When using aspect ratio = auto (c64c ntsc), it shows a 288x288 box. If I use libretro Windows menu to resize to x1 scale again, it correctly shows 288x247.

When using aspect ratio = 1:1, it looks correct. 384x247.

**Comment by sonninnos** [comment]
Sounds like a frontend issue, if fullscreen is fine.

So if the issue is that the window does not scale when changing core options, but scales when changing frontend options, I don't think there is anything to be done core-wise.

**Comment by trioan** [comment]
Frontend seems to only resize the windowed mode when core uses "RETRO_ENVIRONMENT_SET_SYSTEM_AV_INFO" callback. Fullscreen is okay.

I think you're quite right. For now closing.

**Comment by sonninnos** [comment]
Seems logical. Indeed as it is suggested that SET_SYSTEM_AV_INFO is called as rarely as possible in favor of SET_GEOMETRY, currently that only happens dynamically when region changes or when audio sample rate changes. As in all other changes (Zoom + Aspect Ratio) does SET_GEOMETRY.

So sure it could be changed, but should it..?

**Comment by trioan** [comment]
Checked other emu cores with multi-res switching. They only use SET_GEOMETRY for basic resolution, overscan, crop changes. Windowed mode users are expected to use frontend to manually force window resize.

I think it's okay and can stay closed.
