### ISSUE TITLE
vice_xpet wrong key layout

### ISSUE THREAD

**Issue by cucholix** [libretro/vice-libretro#223]
I tested the keys in my latin american keyboard, here are the corresponding keys, virtual keyboard keys doesn't match the actual keys either:

```
Standart KB = PET KB
1 = X
2 = ,
3 = "
4 = \
5 = Q
6 = U
7 = W
8 = I
9 = A
0 = J
' = S
¡ = K
Delete = !
Esc = +
F1 = (
F2 = ;
F3 = Left Arrow
F4 = ;
F5 = S
F6 = ;
F7 = &
F8 = ;
F9 = ---
F10 = On Screen Info
F11 = Virtual KB
F12 = ---
Insert = Z
Supr = 1
Home = M
End = Reset
RePag = ---
AvPag = ---
LockNum = ---
Tab = N
Q = 2
W = $
E = Break Line
R = E
T = 7
Y = R
U = 8
I = D
0 = 4
P = F
` = 5
+ = C
Enter = #
LockCap = Delete
A = ´
D = T
F = Up Arrow
G = Y
H = ---
J = G
K = ---
L = H
´ = B
LShift = DELETE
< = ---
> = ---
Z = )
X = 9
C = 0
V = /
B = P
N = 6
M = L
, = *
. = :
- = 3
\ = Enter
RShift = ;
Ctrl = ---
Alt = ---
AltGr = ---
Arrow Left = ;
Arrow Down = Space
Arrow Right = %
Arrow Up = ;
```
There are still keys I didn't test

**Comment by sonninnos** [comment]
Finally got the time and motivation to look into this. Extra effort was needed to solve the odd fact that certain models use a different layout (graphics/business).

Also fixed the embedded files, so there is no need to copy the data under `system/vice/PET` anymore. Will be in the next PR.

**Comment by paradadf** [comment]
@sonninnos hi! here is the PET keyboard in vector format if it helps in any way:
https://commons.wikimedia.org/wiki/File:PET_Keyboard.svg

**Comment by sonninnos** [comment]
Thanks, it is a bit clearer to read, but won't ease the labor much more than that. C128 should get the VKBD treatment next, I reckon.
