### ISSUE TITLE
Update to v3.4

### ISSUE THREAD

**Issue by carlos-ks** [libretro/vice-libretro#224]
Can you please upgrade to version 3.4

**Comment by sonninnos** [comment]
Why? I checked out the changelog and saw nothing major. It is not a tiny thing to do.

**Comment by sonninnos** [comment]
I guess this can be closed then. Let's look at it again when 3.5 arrives.

This current 3.3 already has some fixes that are not in the "stable" 3.3, so there is no problem including just some essential fixes, if there are any.

**Comment by carlos-ks** [comment]
ok
