### ISSUE TITLE
changing model at run-time does not update automatic aspect ratio

### ISSUE THREAD

**Issue by trioan** [libretro/vice-libretro#225]
I start with c64 pal model at load game and it correctly shows a pal adjusted ar. When I change to c64 ntsc model while core is running, core auto-restarts game with new timing changes. But the auto aspect ratio still draws in pal and not ntsc.

**Comment by sonninnos** [comment]
Works fine here. Are you sure you have RA aspect set at "Core provided"?

![retroarch_2020_04_17_05_49_49_210](https://user-images.githubusercontent.com/45124675/79527288-dca8da00-806f-11ea-8bf7-bdb780d2c90c.png)

![retroarch_2020_04_17_05_50_03_475](https://user-images.githubusercontent.com/45124675/79527295-e03c6100-806f-11ea-9074-6b66b0c17fed.png)

**Comment by trioan** [comment]
Found out it works when "show borders = on". 👍 

When "show borders = off" is when aspect change fails.

**Comment by sonninnos** [comment]
Thanks. I did test it without borders, but apparently not good enough.

I located the reason and fixed it. Will be in the next PR.
