### ISSUE TITLE
Windows: Can only compile x64, others error

### ISSUE THREAD

**Issue by HVR88** [libretro/vice-libretro#228]
In MSYS64 shell, using MINGW, I can build x64 from the current master without issue, with and without specifying it as EMUTYPE, but every single other core produces one or more errors about undefined references (in various files) and fails during linking

Compiling the same code in Ubuntu works for every core.

**Examples**

These all work in Windows for x64:
make -f Makefile.libretro platform=wincross64 -j4
make -f Makefile.libretro
make -f Makefile.libretro EMUTYPE=x64

These all fail in Windows:
make -f Makefile.libretro platform=wincross64 -j4 EMUTYPE=xvic
make -f Makefile.libretro EMUTYPE=xvic
make -f Makefile.libretro EMUTYPE=x128
make -f Makefile.libretro EMUTYPE=x64scpu
etc..

These all work in Ubuntu:
make -f Makefile.libretro EMUTYPE=xvic
make -f Makefile.libretro EMUTYPE=x128
make -f Makefile.libretro EMUTYPE=x64scpu

**Example Error Output**
make -f Makefile.libretro EMUTYPE=x64sc

...
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./vice/src/c64/c64memsc.o:c64memsc.c:(.text+0x2131): undefined reference to `c64scui_init_early'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile.libretro:403: vice_x64sc_libretro.dll] Error 1

**Comment by sonninnos** [comment]
They all work fine here. I also use MSYS, but I've never tried wincross64. Seems like the problem is simply not running `make clean EMUTYPE=x` before making some other EMUTYPE.

I can replicate the issue if I skip the cleaning part. All EMUTYPEs use a lot of the same files, but they will not always deliver the same output.

**Comment by HVR88** [comment]
Damn, I knew it had to be something simple.  I'll give it a shot.  Incidentally, the new crop features/code I mentioned in the other issue has been added and is working very well for c64, I just need to add and test it on the other platforms it can be made to work with.

**Comment by sonninnos** [comment]
But still very odd if the same does not apply to Ubuntu..

**Comment by HVR88** [comment]
Yes, definitely.  Ubuntu is running on a completely different system in a headless VM and I can see the files are created, but at the moment I haven't set up any way to test them.

**Comment by HVR88** [comment]
Verified x64sc compiles and takes all code changes correctly.  Thanks again for the quick response.  Closing.

**Comment by HVR88** [comment]
@sonninnos I believe all cores are compiling with pre-cleaning except x64scpu (XSCPU64) - is there anything special I'm missing for this one?

**Comment by sonninnos** [comment]
No need to give that emutype any attention as it is not currently working anyway.

**Comment by HVR88** [comment]
That's an easy solve, then! :)
