### ISSUE TITLE
x64 defaults fire button to F7

### ISSUE THREAD

**Issue by cucholix** [libretro/vice-libretro#239]
Default core options overwrite the fire button by F7 key, you need to manually change it to empty “- - -“ in order to fire button works in game.

**Comment by sonninnos** [comment]
There is no F7 defined in the default buttons anywhere. Pressing Start on "RetroPad B" makes it "---" here. If not there, please update the core.

**Comment by cucholix** [comment]
It was “retroarch_cores.cfg” fault, stored a previous configuration.

**Comment by cucholix** [comment]
BTW the virtual kb no longer shows with L shoulder, neither joystick/driver status with R. If I use a previous .opt they display fine.

**Comment by sonninnos** [comment]
The current default for VKBD has been Select for a while now. Check out the repo's Readme.
