### ISSUE TITLE
freeze hotkey for action replay cartridge ???

### ISSUE THREAD

**Issue by bigly2001** [libretro/vice-libretro#247]
Hi
I attach Action replay cartridge into lr-vice but i cant use it because i dont know hotkey for freeze 
and i cant assign hotkey

**Comment by sonninnos** [comment]
Oh, I assumed the "soft" reset would do that, but apparently not. I'll look into it.

**Comment by bigly2001** [comment]
thx

**Comment by sonninnos** [comment]
I added the freeze option to reset types, so it can be used by the same hotkey and VKBD button, but if it is too cumbersome in actual use, it can be separated to its own hotkey. VKBD does not have extra room for it though..

**Comment by bigly2001** [comment]
Millions of thanks

**Comment by bigly2001** [comment]
Hi
how can i use this new build of vice in retropie or retroarch?

**Comment by sonninnos** [comment]
According to https://github.com/RetroPie/RetroPie-Setup/wiki/Updating-RetroPie 
`sudo ~/RetroPie-Setup/retropie_setup.sh` does it all. The buildbot build should be available inside 24h after merging, but building from the source is an option too.
