### ISSUE TITLE
D64 not loaded, detected as CRT

### ISSUE THREAD

**Issue by ImJezze** [libretro/vice-libretro#251]
I try to load a D64 disk image with the vice_x64_libretro core on Windows. But the D64 disk image seems to be detected a CRT cartridge image and cannot be opened. If I do the same with the regular Vice executable x64.exe the D64 disk image can be loaded without problem.

This is the retroarch-log.txt
> [libretro INFO] Resource Mouse = 1
> [libretro INFO] Resource AutostartPrgMode = 1
> [libretro INFO] Resource VirtualDevices = 1
> [libretro INFO] Resource Printer4 = 1
> [libretro INFO] Resource SoundVolume = 0
> [libretro INFO] Resource VICIIExternalPalette = 0
> [libretro INFO] Resource VICIIColorGamma = 2500
> [libretro INFO] Resource VICIIColorSaturation = 1000
> [libretro INFO] Resource VICIIColorContrast = 1000
> [libretro INFO] Resource VICIIColorBrightness = 1000
> [libretro INFO] Resource UserportJoy = 0
> [libretro INFO] Resource DriveTrueEmulation = 0
> [libretro INFO] Resource DriveSoundEmulation = 1
> [libretro INFO] Resource DriveSoundEmulationVolume = 400
> [libretro INFO] Resource AutostartWarp = 0
> [libretro INFO] Resource VICIIAudioLeak = 0
> [libretro INFO] Resource KernalName = "kernal"
> [libretro INFO] Resource DosName1541 = "dos1541"
> [libretro INFO] Resource DosName1571 = "dos1571"
> [libretro INFO] Resource DosName1581 = "dos1581"
> [libretro INFO] Resource SidResidSampling = 2
> [libretro INFO] Resource SidResidPassband = 90
> [libretro INFO] Resource SidResidGain = 97
> [libretro INFO] Resource SidResidFilterBias = 500
> [libretro INFO] Resource SidResid8580Passband = 90
> [libretro INFO] Resource SidResid8580Gain = 97
> [libretro INFO] Resource SidResid8580FilterBias = 1500
> [libretro INFO] Resource SidStereo = 0
> [libretro INFO] Arg0: x64
> [libretro INFO] Arg1: E:\Emulation\Images\Commodore - Commodore 64\disk\ENFORCER.D64
> [libretro INFO] Autodetecting image type of 'E:\Emulation\Images\Commodore - Commodore 64\disk\ENFORCER.D64'.
> [libretro ERROR] Cannot open file 'E:\Emulation\Images\Commodore - Commodore 64\disk\ENFORCER.D64'.
> [libretro ERROR] Cannot open file 'E:\Emulation\Images\Commodore - Commodore 64\disk\ENFORCER.D64'
> [libretro INFO] CART: 'E:\Emulation\Images\Commodore - Commodore 64\disk\ENFORCER.D64' is not a valid CRT file.
> [libretro ERROR] Cannot open 'E:\Emulation\Images\Commodore - Commodore 64\disk\ENFORCER.D64'.
> [libretro ERROR] 'E:\Emulation\Images\Commodore - Commodore 64\disk\ENFORCER.D64' is not a valid file.
> [libretro INFO] Image for autostart: E:\Emulation\Images\Commodore - Commodore 64\disk\ENFORCER.D64
> [INFO] SET_GEOMETRY: 384x272, aspect: 1.322.
> [libretro INFO] UI finalized now
> [INFO] [Environ]: GET_PERF_INTERFACE.
> [libretro INFO] Opened device `retro', speed 48000Hz, fragment size 0.7ms, buffer size 2ms
> [libretro INFO] reSID: MOS6581, filter on, sampling rate 48000Hz - resampling, pass to 21600Hz

**Comment by sonninnos** [comment]
No, it is not detected as CRT either. That is just the regular order of things that VICE does when it fails at each step. It clearly does say "Cannot open file" multiple times, so something is wrong with the file.

Here it goes like this:
```
[libretro INFO] Arg0: x64sc
[libretro INFO] Arg1: s:\emu\c64\img\beli\Wizard.d64
[libretro INFO] Autodetecting image type of `s:\emu\c64\img\beli\Wizard.d64'.
[libretro INFO] Attached file `s:\emu\c64\img\beli\Wizard.d64' as a disk image.
[libretro INFO] Autodetected image type 1541.
[libretro INFO] Resetting the machine to autostart '*'
[libretro INFO] `s:\emu\c64\img\beli\Wizard.d64' recognized as disk image.
[libretro INFO] Image for autostart: s:\emu\c64\img\beli\Wizard.d64
[libretro INFO] Image list is active for drive #8
[libretro INFO] Image list has 1 file(s)
[libretro INFO] File 1: s:\emu\c64\img\beli\Wizard.d64

```

**Comment by ImJezze** [comment]
The file is valid, and I found out the real reason for the problem, which is kind of weird.

The problem was the minus sign in the file path. It was not the usual minus sign (HYPHEN-MINUS, U+002D), but somehow I managed to use the "soft" variant (SOFT HYPHEN, U+00AD) when creating the folder.

**Comment by sonninnos** [comment]
Heh, nice.

**Comment by ImJezze** [comment]
I close this issue then. Thanks!
