### ISSUE TITLE
Joystick button not recognized

### ISSUE THREAD

**Issue by Shoegzer** [libretro/vice-libretro#255]
Can't start the game "Boulder Dash" with the x64sc core as joystick button presses do not appear to be recognized.  When turning on the status bar at the bottom of the screen, I see a visual indicator for the D-Pad presses (up, down, left, right) but not for the button, which I have set at "B".  Not sure if it's something I'm doing wrong here but I've tried different configurations.  Tested with DS4 pad mapped as both "RetroPad" and "Joystick".

@sonninnos any thoughts or suggestions here?  Thanks!

**Comment by sonninnos** [comment]
It is one of those joyport1 games. Also need to press F1 first at the menu.

**Comment by Shoegzer** [comment]
Thanks, I figured as such too and set the port to 1 while testing.  After pressing F1, button is still not recognized though.

**Comment by sonninnos** [comment]
All versions work fine here, don't know what else could be up..

**Comment by Shoegzer** [comment]
Thanks @sonninnos.  I tried your suggestions though and still can't get the fire button to register.  My inputs are all at default RetoPad maps.  I tried changing to "Y=Fire, B=Up" but it didn't help.  

Any other suggestions you may have toward troubleshooting or resolving this would be extremely appreciated.  Perhaps you could retest to see if you could reproduce this with the latest build?  I'm using 642b653cddc2032a4f5b7f028b7cce36a3e5a4ae.  Thanks so much.

**Comment by sonninnos** [comment]
I'm always using the latest build, and as I said, I can only reproduce the fire button not firing if I map a keyboard key in its place under core options..

**Comment by Shoegzer** [comment]
Ah, I see what you're saying now.  I missed the "Show Mapping Options" setting, which of course revealed the mappings after I toggled that on.  And yes, "RetroPad B" is unfortunately mapped by default to "RETROK_ESCAPE".  Turning that to "---" gave me the fire button.  Thanks!

That said, a few comments here:

First, I think the "Show Mapping Options" setting shouldn't exist, but rather expose the mappings automatically.  

Second, I think the mappings for the pad should all be turned off, which I believe would enable the directions and one fire button as an actual Commodore joystick would be.  The user could then map them to hotkeys as they desire.  As it stands, any first-time user of this core would need to know to turn the "Show Mapping Options" feature on, and also to unmap the fire button that is default-mapped to something else, before they can begin using the joystick as it should be used.

Third, and this may be more of a general RA comment than anything specific to this core, but I really wish there could be a more intuitive way of configuring inputs in RA.  Here the user is faced with *three* different areas to change settings:

1. Quick Menu > Options (after "Show Mapping Options" is turned on)
2. Quick Menu > Controls > Port X Controls
3. Settings > Input > Port 1 Binds

...and the question of what options do what is confusing and left to the user to figure out.  

IMO, ideally the amount of settings should be reduced and then consolidated into the "Settings" area as it would make a lot more sense.  For example, having core-specific settings *inside* the "Settings" area rather than "hiding" them inside "Quick Menu" (what does that even mean?) which only appears once a core is launched(!).  Veteran users eventually find ways to work with this counter-intuitive structure, however it spikes the learning curve unnecessarily and just makes setting things up a constant chore, especially in complex scnerios like computer systems.

**Comment by sonninnos** [comment]
But the default already is and has been "---" for most of the buttons. Only L2 and R2 are RETROK_ESCAPE and RETROK_RETURN. Pressing RetroPad Start at the option resets it to the default.

So looks like you have managed to run the core for the first time at a so called bad time in regards of those defaults. (I can't remember a time when B was ever Escape though).

And the reasoning for hiding them by default is of course the fact that the list is very long.

Sure it is confusing at start, but it is the best way for now. Can't do much to go around the way RA is designed when it comes to combining joystick and keyboard keys.

**Comment by Shoegzer** [comment]
Interesting.  Almost all of mine are mapped, and L2 and R2 were set to "RETROK_KP_MULTIPLY" and "RETROK_ESCAPE" respectively.  Strangely, I had Select mapped to "RETROK_F11" but it still gave me the VKBD.  However when I reset it, it defaulted to "TOGGLE_VKBD" and still worked.  Not sure why it was mapped that way, you might be right that I cloned the repo at the wrong time once before but whatever the case it seems to be fine now.  Thanks for your help.

I'd prefer to not have them exposed regardless of length, but that's a matter of personal preference.  Ideally the core "Options" menu could have separate sub-areas for Input, Audio, Video, Misc etc. which would make the list even shorter and easier to navigate but perhaps that's an RA limitation preventing that?

I appreciate and agree with your thoughts regarding RA design, and I figured it's beyond the scope of this core for sure.  Even if the "Quick Menu" could be located as a Settings submenu and only populated when a core is launched, that would be more intuitive than what we have now as it's just out of place under "Main Menu" when most of what's there is more settings-related.  Again I realize it's not your issue, just thinking through options out loud in the context of a core that could really benefit from such RA-wide improvements.  Would you agree?

**Comment by sonninnos** [comment]
Then the config must be very old, I don't recall setting "RETROK_KP_MULTIPLY" to anything ever.

F11 is mapped to bring up the VKBD by default, so of course both should work. The direct "TOGGLE_VKBD" is a recent addition, and as you noticed already, any new defaults will not replace the ones that were defaults when the config is created (unless the option is no longer available at all).

Yep, there are no sub-menus for core options yet in RA, that is why this clunky hiding exists in the first place. But sure, perhaps I should remove even the L2 and R2 defaults, and make the mapping options always visible. Then again RUN/STOP and RETURN are pretty often needed, and they aren't in the way much there.

Personally I have the right analog stick mapped as the ultimate cracktro/trainer skipper: up&down=Y/N, left&right=L/R, L3=H, R3=T (L for load hiscores, R for reset hiscores, H for hiscore, T for trainer). They also were the defaults for a while, but we decided to null them to minimize extra confusion for new users.

And I don't know, I'm pretty comfortable with the way RA keeps core related settings separated from frontend related. I'm way too deep in the swamp to try to successfully wear objective-fresh-perspective boots, heh.

**Comment by Shoegzer** [comment]
Ah, I see now.  I had missed that F11 is the vkbd toggle but what you say makes sense.

Glad you agree on sub-menus being beneficial, it's too bad they aren't there but I'll probably submit a feature request for such a thing soon as I think it would provide a nice benefit especially here.  

I think you made the right decision to null the options for new users, but the trainer/skipper mapping for right analog is actually a neat idea for those who want to remap.

I do agree that core settings should be separate from frontend settings, I just think they should be contained *within* the settings area of RA under a separate "Per-Core Settings" submenu.

In any event I think it's safe to close this issue so I'll do that now lest this distract unnecessarily.  Thanks again for your help and thoughts, as always.
