### ISSUE TITLE
libretro_vice_x128   core   Android version

### ISSUE THREAD

**Issue by gigibyte236** [libretro/vice-libretro#258]
version 1.8.8 starts but the screen after the initialization of the 80col (vdc) mode remains black. you don't see the 40col mode (vicii). if you switch to 80col mode with the f7 key and reset this mode works. vicii mode is visible only by forcing the c64 mode from the settings but in this case it is the c64 compatible mode (classic c64 screen)

**Comment by sonninnos** [comment]
I can't reproduce with Windows. Please provide a verbose log. Probably something to do with the funky VDC resolution the machine inits with no matter what.

```
[INFO] SET_GEOMETRY: 856x288, aspect: 2.784.
[libretro INFO] UI finalized now
...
[INFO] SET_GEOMETRY: 384x272, aspect: 1.322.
```

And yep, that F7 switcher needs to be looked at, as it does not change the aspect ratio like it does with the core option switch.

**Comment by gigibyte236** [comment]
[retroarch.log](https://github.com/libretro/vice-libretro/files/4724906/retroarch.log)
the windows version works regularly
I tried on android on 2 different devices, and also on the bluestacks emulator with no positive result

**Comment by gigibyte236** [comment]
I add information if they can be useful, with Retroarch ver 1.8.9.
I downloaded from buildbot.libretro.com/nightly/android/2220-05-50_cores/armeabi-v7a the core vice_x128_libretro_android.so comit 685e93b of 4 / may / 2020 and installed with the appropriate  function install / restore cores from local path. this is the latest version of the core that works correctly, that is, at startup after the initialization of the vdc it switches to the 40 column screen of the vicii. the basic 7.0 instruction "Graphic 5" and "Graphic 0" work regularly and change between the two video modes

**Comment by sonninnos** [comment]
Thanks. I had a look at the next commit and could not find anything C128 and/or Android related, so I'm stumped..

**Comment by gigibyte236** [comment]
Hi , on android you can select the video driver gl or vulkan. but only gl works.

there are 4 commits between the working core and the one that doesn't work which is commit 764add2.
I also saw that in the code there are no changes in the part that provides the switch between the vdc and the vicii ...
I wanted to compile the core myself with the changes of the commits one at a time, but it gives me an error on some "includes" that it does not find (only on the vice cores, fbneo worked ... I have no luck).
Is it possible to know if the buildbot.libretro.com build environment has been updated? I had this doubt because the compilation instructions for android refer to sdk 28 while we are now at version 30.

**Comment by sonninnos** [comment]
I have no idea about buildbot, as the logs are only shown when a build fails..

What includes are missing?

@rsn8887 Do you still have that android toolchain ready for testing with this?

**Comment by gigibyte236** [comment]
sorry, my idea on buildbot was nonsense .. i found that on windows the android toolchain needs ndk-build with suffix .cmd so the errors on the missing includes are gone, but windows also has a limitation on the length of the strings, so I was unable to compile successfully. I switched to Ubuntu and once installed android sdk I was finally able to correctly compile the core ...
I can confirm you that commit 685e93b is the last one that works. starting from commit 6b42e1f "sync finetuning" the exchange between vdc and vicii does not work.

**Comment by sonninnos** [comment]
Nice! Could you try disabling those added `#ifdef __LIBRETRO__`s in `vice/src/vsync.c`?

**Comment by gigibyte236** [comment]
i tried. so it works!

**Comment by sonninnos** [comment]
What a lucky shot, excellent! Those were put in place for the internal warp to function properly, so let's hope the workaround will also be simple.

**Comment by sonninnos** [comment]
Luckily it won't affect the warp operation at all, but only the FPS value during warp in the statusbar. I'll just remove them altogether and not make an exception for only Android.

**Comment by sonninnos** [comment]
Could you please test if this change achieving the same result still works before I PR it, thanks!
https://github.com/sonninnos/vice-libretro/commit/a1e8f06bb12cab43d428319b5cfc533efea2fe6c

**Comment by gigibyte236** [comment]
I compiled the change to the code, the exchange between the vdc and the vicii works as expected.I had not seen it before but now the status bar shows the FPS while before it varied between the value 0 and 1. great job, thanks
