### ISSUE TITLE
Mouse cursor is non-functional

### ISSUE THREAD

**Issue by quicksilver7837** [libretro/vice-libretro#26]
It seems that the mouse/mouse cursor is not functional. I am able to open the on screen keyboard and I can open the vice gui. But I am not able to make any selections because there is no mouse cursor (it doesnt even display on the screen). I tested using a wireless mouse and I also tested with my xbox360 controller and neither work.

**Comment by lodgerz** [comment]
to move mouse curson with xbox360 controller you need to press SELECT (Back) button, but first you must to configure it on Input setting.

**Comment by quicksilver7837** [comment]
Yes I know. I am saying that in the current version, this is not functioning properly. Pressing select is not bringing up the mouse cursor.

**Comment by lodgerz** [comment]
you have to move d-pad a little before mouse cursor appear.

**Comment by quicksilver7837** [comment]
What version of Lr-vice are you using? Have you updated from source recently? It seems that the mouse cursor is not visible in the current build. A link to a thread I started on the issue: https://retropie.org.uk/forum/topic/15817/navigating-lr-vice-gui/78

**Comment by lodgerz** [comment]
i have no raspberry, i don't know what is lr-vice.

**Comment by rsn8887** [comment]
I also cannot control the Nuklear GUI that pops up with "start" with a game controller. There's no mouse pointer, I cannot select anything. I cannot close the GUI overlay either. If I press x to bring up the virtual keyboard, also in Nuklear GUI, I cannot control that either, apart from closing it again.

**Comment by quicksilver7837** [comment]
This issue appears to be resolved. I just updated from source today and my mouse cursor is visible and functional again.
