### ISSUE TITLE
libretro_vice_xplus4 loading .prg not valid option for -cart

### ISSUE THREAD

**Issue by snte** [libretro/vice-libretro#262]
When trying to load a .prg (with autostart) in libretro_vice_xplus4 (RetroArch 1.8.8) I get the error: 
`Argument 'PATH/FILENAME.prg' not a valid option for -cart`

Tested this on Switch, Android, MacOS, and tracked it down to the following Nightlies

This ist the last nightly it works (2020-05-**20**): https://buildbot.libretro.com/nightly/nintendo/switch/libnx/2020-05-20_RetroArch.7z

The error starts with this (2020-05-**21**): 
https://buildbot.libretro.com/nightly/nintendo/switch/libnx/2020-05-21_RetroArch.7z

By the way, thanks to all the developers for this wonderful core!

**Comment by sonninnos** [comment]
Oops, I should've tested more file formats when the cart support was fixed.

And thanks for the thanks!
