### ISSUE TITLE
Automatic Load Warp causes t64 tape images to run as if stuck in warp mode

### ISSUE THREAD

**Issue by NascentTech** [libretro/vice-libretro#263]
Retroarch 1.8.9, vice x64sc. If Automatic Load Warp is enabled for t64 tape images then the program will run as if stuck in warp mode. Disabling Automatic Load Warp allows for normal run behavior.

**Comment by sonninnos** [comment]
Thanks for reporting. For some reason VICE does not properly stop the tape motor with that fake tape format, which of course throws the automagic off. Pressing the Datasette Stop button/hotkey stops the motor by force, but I'll figure out a proper fix.
