### ISSUE TITLE
Disk image corruption when using different format disk images

### ISSUE THREAD

**Issue by NascentTech** [libretro/vice-libretro#267]
This has occured under very specific circumstances and can be reproduced.
retroarch 1.8.9, x64sc

Running a two disk game (Demon Stalkers)
disk side 1 is D64 image, disk side 2 is G64 image.
1) Load and start game. 
2) Insert disk side 2 to play.
3) Enter disk options (S) and F5 to save game.
4) Exit and restart game.
5) Insert disk side 2 to begin play, but disk is no longer recognized and image is corrupted.

Likely cause is due to a mix of disk image types.  Tested this using winvice 3.3 and 3.4 and there are no issues.

**Comment by sonninnos** [comment]
Indeed something is funky in the disk format / drive type detection during disk changing, even if the drive type should stay the same in this case.

1. Playlist of a single G64 = write works
2. Playlist of two disks, first G64, second D64 = write works
3. Playlist of two disks, first D64, second G64 = write does not work

Though in these tests the disk was not corrupted, but only it did not write anything. But this was with empty disks (G64 was converted from a D64), so the outcome is most likely different with actual data..

Luckily there also exists a single-sided cracked version of that game (only one I could find).
