### ISSUE TITLE
Game not loading/hanging, but works with Winvice 3.3

### ISSUE THREAD

**Issue by NascentTech** [libretro/vice-libretro#269]
This is, so far, a game specific issue with the game Racing Destruction Set.  I have tried several different image sets, but none appear load or run correctly.

Tested unknown source g64 set and TOSEC version d64 set.  These hang at the EA loader.
Attempted to load some of the cracks from the TOSEC set, but these result in a dump back to prompt.
Found no issues when testing with Winvice 3.3.
Can anyone confirm this issue?

**Comment by sonninnos** [comment]
I tried the BCS cracked version and the EasyFlash version and both proceeded to the racing part just fine, in PAL and in NTSC.

**Comment by NascentTech** [comment]
After further testing this appears to load correctly if the machine is set to "C64c PAL" or "C64c NTSC".  Loading still hangs if the machine is set to original C64.
Tested BCS cracked version again and now it seems to run?

**Comment by sonninnos** [comment]
I managed to make the BCS version to not work if True Drive Emulation is disabled. I use(d) the default C64 PAL.

**Comment by NascentTech** [comment]
Still seeing difference between C64 and C64c.

Using TOSEC "Racing Destruction Set (1985)(Electronic Arts)(Side A).d64"
True drive always on.  No jiffyDOS.  Start with machine set to C64c NTSC and no problems.  Switch to C64 NTSC and restart and it  hangs.  Switch back and restart, no problem again.

But, if the issue cannot be recreated, then there is not much that can be done.

**Comment by sonninnos** [comment]
Tried that version too and it also works fine with the default C64.

**Comment by NascentTech** [comment]
Since this cannot be recreated, then there is no reason to keep it open.  If I am able to isolate this any better then i'll revisit the issue at a later time
