### ISSUE TITLE
Mouse not working correctly.

### ISSUE THREAD

**Issue by n1ghttrap** [libretro/vice-libretro#274]
Used Rogue and Lemmings as my test cases.  Rogue only moves the mouse cursor upward on 1351 mouse mode when I press B (fire) on my controller.  Amiga mouse and trackpad act erratically and unresponsive when I move the mouse but it does seem to be accepting my input to some extent and very vaguely goes where I tell it. I can't get the mouse to move at all in Lemmings regardless of mode. Latest core and Retroarch used as of this post.  Mouse in other cores is working perfectly fine, such as in Mario Paint via SNES9x.

**Comment by sonninnos** [comment]
Lemmings is working fine here. I can't find a version of Rogue that would support mouse, so if there is no support, no wonder it does not work properly.

Use this to confirm: https://commodore.software/downloads/download/148-c64-testers/8665-mouse-test-2

**Comment by n1ghttrap** [comment]
I'll go ahead and close it.  At the very least that test works for me so I'll presume that it's a configuration or software issue on my end for Lemmings.  Thanks.

**Comment by sonninnos** [comment]
Maybe there is a version of Lemmings that does not support mouse..? I tried the EasyFlash version.
