### ISSUE TITLE
CRT emulation / scanlines etc?

### ISSUE THREAD

**Issue by runvnc** [libretro/vice-libretro#28]
Hello, this is great.

I have been trying to figure out how to get CRT emulation/scanlines etc.  I have tried copying over Vice dirs and config files and stuff.  Maybe its not possible?  If it is possible, or possible to add it, can I get a hint what code of config stuff to mess with.

Thanks!

**Comment by lodgerz** [comment]
to set CRT emulation on retroarch you need to install GLSL shaders: "Online updater"->"Update GLSL Shaders". than in Quick Menu go in "Shaders"->"Load Shaders Preset". my favorite CRT emulation is "shaders_glsl/crt/crt-pi.glslp".
![giana sisters-180123-110040](https://user-images.githubusercontent.com/9266267/35269475-665dd73a-002c-11e8-99f5-e37a8e519437.png)

**Comment by runvnc** [comment]
Thanks..I'm not using RetroArch, it's my own 3d front end.  Eventually I
will get around to the shaders stuff for the screens.
