### ISSUE TITLE
XVIC command line paths are annoying

### ISSUE THREAD

**Issue by sionisaac** [libretro/vice-libretro#284]
I have been trying to run the Vic20 megacart rom using the following command line options saved in a cmd file:

xvic -cartmega /path/to/rom/mega-cart-name.rom

I'm on Windows 10 latest retroarch and latest Vice cores.  If I put the rom in a folder that contains a hyphen e.g. (Commodore - VIC-20) it refuses to load the rom with the message Argument 'Path to rom' not valid for option '-cartmega' . 
If I put the rom on the root of the drive and alter the path in the cmd file it works.  I don't want to have this file in my root and I may move it to another drive later.  Is there any way to create a cmd file that will reside in exactly the same folder as the rom and run it without setting any path in the cmd?

**Comment by sonninnos** [comment]
Just wrap the path with quotes:
`xvic -cartmega "/path/to/rom/mega-cart-name.rom"`

I'll make that automatic somehow soon, so that there is no need to hassle with cmds. Something like if the name has "mega" in it, it'll do `-cartmega`.

**Comment by sonninnos** [comment]
All right, that should cover both of those problems:
- Mega-Cart can be launched directly, and it saves NvRAM to `saves` automatically
- `.cmd` can be used without absolute paths
