### ISSUE TITLE
[Request] Virtual Keyboard with joypad

### ISSUE THREAD

**Issue by lodgerz** [libretro/vice-libretro#29]
Hi,
are you able to make virtual keyboard controllable with joypad?
Thanks.

**Comment by r-type** [comment]
it is. you have to push select to toggle mouse/joypad

**Comment by lodgerz** [comment]
oh, iI didn't know. thanks.
maybe would be better to insert a text like "Press SELECT to swap mouse/joypad" in the virtual keyboard window.

**Comment by quicksilver7837** [comment]
@lodgerz - Did this work for you? After updating lr-vice it seems that pressing select no longer toggles the mouse cursor for the game pad. Mouse cursor doesn't even appear onscreen for me anymore.

**Comment by lodgerz** [comment]
yes, you have to move d-pad a little before mouse cursor appear.
