### ISSUE TITLE
75Hz (scrolling problem)

### ISSUE THREAD

**Issue by lodgerz** [libretro/vice-libretro#30]
Hi,
I have noticed that if i set 75Hz refresh rate on my TV, the scrolling of retroarch+libretro-vice is very bad.
With stand-alone vice 3.1 instead it works perfectly as if it was 50hz.
I can't set 50Hz because my TV support only 60 and 75Hz refresh rate:

```
$ xrandr
Screen 0: minimum 320 x 200, current 1024 x 768, maximum 8192 x 8192
VGA-1 connected primary 1024x768+0+0 (normal left inverted right x axis y axis) 708mm x 398mm
   1280x720      50.00 +
   1024x768      75.03*   70.07    60.00  
   832x624       74.55  
   800x600       72.19    75.00    60.32    56.25  
   640x480       75.00    72.81    66.67    59.94  
   720x400       70.08  
DP-1 disconnected (normal left inverted right x axis y axis)
HDMI-1 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)
HDMI-2 disconnected (normal left inverted right x axis y axis)
```

```
$ lspci|grep -i vga
00:02.0 VGA compatible controller: Intel Corporation Atom Processor Z36xxx/Z37xxx Series Graphics & Display (rev 0e)
```
if i set 60Hz is worse than 75Hz.
Audio and video vsync are enabled on retroarch.
I use X. With wayland, scrolling is little better.

```
$ cat ~/.vice/vicerc
[C64]
WindowTopHint=22
WindowBotHint=26
ConfirmOnExit=0
Window0Width=720
Window0Height=592
Window0Xpos=0
Window0Ypos=26
Sound="1"
SoundDeviceName="retro"
SoundBufferSize=100
VirtualDevices=1
IECReset=1
CIA1Model=0
CIA2Model=0
VICIIHwScale=0
VICIIVideoCache=1
VICIIFilter=0
SidEngine=0
SidModel=0
KeySet1North=65362
KeySet1East=65363
KeySet1South=65364
KeySet1West=65361
KeySet1Fire=122
JoyDevice2=4
DriveTrueEmulation=0
DriveSoundEmulation=1
```
retroarch.cfg:
https://paste.linux.community/view/2fff2a2a

**Comment by lodgerz** [comment]
I did some tests with git checkout. the problem starts from this commit:
https://github.com/libretro/vice-libretro/commit/6d7703ce489e762bc2f7acbfde1bdeb9a27cfb69

in old version the scrolling is better.

**Comment by modeler** [comment]
I recently noticed that the VICE x64 gave perfect scrolling on my 60 Hz display, at which point I realised it was running too fast. Even though I'm emulating a PAL C64 and the status bar says 100% / 50 FPS, it was running at 60 FPS. I need to experiment to see if this is something I can control, will raise a separate bug report if necessary.

**Comment by modeler** [comment]
I was able to reproduce this, but I'm not a developer so I can only verify the issue. However, I did find that the issue is only present in Windowed Mode. If you set Windowed Fullscreen Mode to OFF, scrolling is much improved. The same is true when running in KMS mode.

The core seems to make RetroArch go out of sync with the compositor, although as you say builds from earlier commits don't seem to have such problems.

**Comment by rsn8887** [comment]
Can you check if this is still an issue for you, using latest core version? Use Online Updater->Update Cores. Thanks!

**Comment by rsn8887** [comment]
This was fixed recently. The frame timer is now more accurate, for example it is not 50 Hz PAL, but 50.1 or so now, and changes correctly to 60 Hz-ish when 60 Hz NTSC model types are selected.

**Comment by rsn8887** [comment]
Please test and add a comment here if this is still an issue for you, and I will re-open the issue, @lodgerz, @modeler . Thanks.
