### ISSUE TITLE
Specify PRG When Loading From .m3u

### ISSUE THREAD

**Issue by Zombeaver** [libretro/vice-libretro#304]
This isn't something that's likely to be needed often, but there are instances where it would be useful to be able to specify the PRG that you want to load from a disk that's indicated in an .m3u. For single-disk games I use .cmds that contain:

x64 -autostart "Game.d64"

If needed, this can be changed to something like:

x64 -autostart "Game.d64:specificprogram"

This inserts that specific program name in place of "[asterisk]" and works fine. I don't know of a way to replicate this in a scenario where you're loading multiple disks in an .m3u though. Case in point, Newcomer is _14 disks long_ including the boot disk, and it has a very long unskippable intro if you just let it use "[asterisk]", but if you tell it to load "newcomer" it skips it. At the moment I'm using a savestate to deal with this but preferably there would be a way to use something like the following in an .m3u:

Boot.d64:newcomer
SideA.d64
SideB.d64
etc.

If there's already a way to do this, my apologies, but I haven't found it yet.

**Comment by sonninnos** [comment]
Apparently it is already possible, but zero mention in the Readme..

Example m3u:
```
#COMMAND:x64sc "Ghost of Genghis Khan, The.d64:k6"
Ghost of Genghis Khan, The.d64
```

I sure like the syntax in your example more, so perhaps I could make that work too. I had nothing to do with this current method.

BTW `-autostart` is not needed, and also that command method will not survive any kind of restart.

**Comment by Zombeaver** [comment]
> #COMMAND:x64sc "Ghost of Genghis Khan, The.d64:k6"
> Ghost of Genghis Khan, The.d64

>I sure like the syntax in your example more, so perhaps I could make that work too. I had nothing to do with this current >method.

Hmm yeah that's kindof ugly but if it works it works. I'll experiment with that.

>BTW -autostart is not needed

It was in older versions, doesn't seem to hurt anything in the current version.

> that command method will not survive any kind of restart.

It doesn't really need to for my purposes, the games are all started via a front-end (Launchbox) which is hooked up to a .vbs > .bat > .cmd or .m3u > disk; and I'd need a major refactor to get rid of them. I'm using them in 1,982 cases currently.

**Comment by Zombeaver** [comment]
So that does indeed work for specifying the program in an .m3u. However, that doesn't survive a restart or reset either. It literally doesn't enter anything to load at all when telling it to restart.

I'm also not sure what the correct syntax would be to do this with a single disk through command line. You can of course setup an .m3u for just the one disk and it'll work but seems like there should be a better way.

**Comment by Zombeaver** [comment]
Something seems to have gone wrong in the update. Now .cmds don't pull the specific program at all unless you tell it to reset after starting i.e. loading a .cmd of "Disk1.d64:k6" from the example above just loads "*" but if you press End to reset then it loads K6.

**Comment by sonninnos** [comment]
Oops, fixed in the next batch.

**Comment by Zombeaver** [comment]
Great, thanks!
