### ISSUE TITLE
Manual Warp Not Working When Automatic Load Warp Is Enabled

### ISSUE THREAD

**Issue by Zombeaver** [libretro/vice-libretro#306]
I've been experimenting with Automatic Load Warp lately with games that require TrueDrive - this is a _great_ feature, thank you for implementing it; that was the only thing that CCS64 used to be able to hold up as an advantage over other C64 emulators, it was called "Maximum 1541 Speed" there - but one odd thing I've noticed about it is that so long as the option is enabled, manually activating warp (PgDn) doesn't work correctly. It will basically warp for about half a second and then stop so you end up having to just tap it repeatedly rather than holding it down like you would normally. I'm assuming/hoping this is unintentional.

**Comment by sonninnos** [comment]
I did not bother adding the ability for ALW to not take total control over the warping, but I guess I could try..

**Comment by Zombeaver** [comment]
If they're mutually exclusive so be it, I would rather have ALW as it is now without manual warping ability (since you can still fast forward at least) than the other way around, but I just found the behavior odd. It works, but there are times where one might want to warp forward even if data isn't being loaded.
