### ISSUE TITLE
No two player support

### ISSUE THREAD

**Issue by rsn8887** [libretro/vice-libretro#31]
Two players simultaneously doesn't work. I can switch one player from joystick port 1 to 2, but I cannot play with two players simultaneously. Or maybe I am just unable to figure out how to enable the second player.

**Comment by rsn8887** [comment]
I think https://github.com/libretro/vice-libretro/pull/33 should fix this, but my knowledge of libretro input API is extremely limited.

**Comment by twinaphex** [comment]
I merged your PR. Are there any remaining issues with it for which you require help from other people or do you think it's fine as-is?

**Comment by rsn8887** [comment]
I think it should be fine as is.

**Comment by rsn8887** [comment]
Tested and it seems to work just fine.
