### ISSUE TITLE
Stereo SID Support

### ISSUE THREAD

**Issue by Zombeaver** [libretro/vice-libretro#310]
The core currently has dual SID support but (unless there's some option that I haven't found yet) the output is still in mono. Most if not all 2SID tracks are designed to be played in stereo with each SID acting as left and right channels. The end result is very different from what you get in the core currently.

Some examples that you can test out for yourself:

[Electric City by Flex](https://csdb.dk/release/?id=189742)

[Stars Are Us by Jammer](https://csdb.dk/release/?id=174760)

For comparison I'd recommend checking out the excellent [libsidplayfp](https://sourceforge.net/projects/sidplay-residfp/) with the ini set to stereo mode or starting the track through command-line with the -s switch.

**Comment by sonninnos** [comment]
It is forced mono for now due to current ReSID-fp not playing ball with it for some unkown reason..

**Comment by Zombeaver** [comment]
I definitely hope there's a way to resolve that. Most 2SID tracks sound _pretty bad_ in mono. Is there no way to do stereo in VICE? Many standalone SID players support it, I'm surprised that VICE doesn't if that's the case.

**Comment by sonninnos** [comment]
Standalone does stereo fine, so it is doable here too, but then again it does not have ReSID-fp.

**Comment by Zombeaver** [comment]
Hmm, well I suppose standard ReSID + Stereo is going to sound better than ReSID-fp + mono for 2SID tracks so that would still be something. ReSID-fp stereo would certainly be preferable though.
