### ISSUE TITLE
Resid engine is extremely slow only in this core.

### ISSUE THREAD

**Issue by rsn8887** [libretro/vice-libretro#32]
Enabling resid causes large slowdown. Other ports of Vice (PSPVice etc.) do not show this slowdown with resid enabled.

**Comment by r-type** [comment]
resid emulation is slow even on i5/i7 core with vice 3.0/3.1 . this is the most demanding cpu part of this emulator . and i 'm not aware there is an vice 3.0 core in psp .
check the standalone vice and you will see how resid enable is slow.

http://csdb.dk/forums/index.php?roomid=7&topicid=124018&showallposts=1

**Comment by rsn8887** [comment]
I see. I didn't realize resid became so much slower between 2.2 and 3.0. Vicepsp is based on 2.2 and resid runs at full speed. One solution would be to offer the old faster resid as an option (6581ro or something), since it still sounds miles better than fastsid. Fastsid sounds horrid :)

**Comment by rsn8887** [comment]
Resid emulation might have gotten a lot faster between in 3.2, because latest VicePSP (bumped to 3.2) can run resid without slowdown on a PSP (!). So this might be another reason to somehow update this core to 3.2

**Comment by rsn8887** [comment]
Hmm the core is on v3.3 now, and the Vita still struggles with ReSID just as before. So it is not an issue with the Vice version, maybe the Vita is just too slow for ReSID.
