### ISSUE TITLE
Savestates Break Easyflash Saving

### ISSUE THREAD

**Issue by Zombeaver** [libretro/vice-libretro#329]
Loading from a savestate seems to break saves made to easyflash carts. An example would be [Deja Vu & Uninvited](https://csdb.dk/release/?id=148695). If you start the game, play for a bit and then save, exit, restart and load a save game from the cart it will load fine. If you start the game, save state, play for a bit then save to the cart, exit, restart, load the state and then try to load a save from the cart it doesn't work (it just starts from the beginning). I've noticed this in other instances like [Zak McKracken & Maniac Mansion](https://csdb.dk/release/?id=98674) too.

**Comment by WindyWinston** [comment]
> If you start the game, save state, play for a bit then save to the cart, exit, restart, load the state and then try to load a save from the cart it doesn't work

Probably because the state that you loaded was before you saved to the cart ? I would only use one or the other, or make a save state after you save to the cartridge so the changes are saved in the state.

**Comment by sonninnos** [comment]
Kinda sounds like a job for VICE devs and not libretro particularly. As in after using a savestate it no longer uses the file itself anymore, but a copy (state size with carts is way bigger than normal, because all memory data is included, like the disk data with the d64 disk states).

I could try looking at it though, even if I'd never use it, which is why I haven't even tried.

**Comment by Zombeaver** [comment]
> Probably because the state that you loaded was before you saved to the cart ? I would only use one or the other, or make a save state after you save to the cartridge so the changes are saved in the state.

Except that same procedure with disk-based saving works just fine.

> Kinda sounds like a job for VICE devs and not libretro particularly. As in after using a savestate it no longer uses the file itself anymore, but a copy (state size with carts is way bigger than normal, because all memory data is included, like the disk data with the d64 disk states).

This may be the case but, if so, it's only an issue for easyflash (or perhaps cart in general) specifically. I can point you towards disk games that save and load just fine in combination with savestates if need be.

**Comment by sonninnos** [comment]
Well, like I said, carts and disks/tapes are apples and oranges from VICE's point of view. AFAIK there are no regular carts that have flash memory, so most likely that EF save support is simply half baked regarding snapshots/savestates. 

Who knows, maybe it is already fixed on current versions. So please do try out what happens with latest 3.4 standalone.

**Comment by Zombeaver** [comment]
Here's a quick video demonstrating save states + disk saving. The state is saved at the title screen and set to auto-load (state.auto), and this was done before any saves have been made to the disk. A save is then created, I quit, reload that same state, and load from the disk no problem. Everything works as I would expect there.

https://www.youtube.com/watch?v=t6v2vY_dYsk

This same procedure with an Easyflash like those I linked doesn't work. My guess is that, as you said, it's not actually saving to the cart in that case, it's probably just temporarily saving it into memory.

> most likely that EF save support is simply half baked regarding snapshots/savestates.

That's certainly possible.

> Who knows, maybe it is already fixed on current versions. So please do try out what happens with latest 3.4 standalone.

I'll take a look.

**Comment by Zombeaver** [comment]
Yeah it doesn't work in standalone either.

**Comment by sonninnos** [comment]
Bummer. Which means I have to conjure it up then. So let's hope it is at least as simple as that recent disk state hassle..

**Comment by Zombeaver** [comment]
There's plenty of stuff in the core that doesn't exist in standalone either. I have faith :smile:

If there's nothing that can be done, so be it, but I wouldn't put it past you. Would be worth a look at least.

To clarify why I even want this, some Easyflash games like Deja Vu + Uninvited are multi-game carts. C64 Dreams is setup in such a way that every game has it's own launcher and I prefer not to have those start up to a menu where you're choosing a game (as this sortof defeats the point). In cases where no in-game saves are involved to begin with it's a non-issue, but there are a few edge cases like the ones I mentioned where it would be useful.
