### ISSUE TITLE
[Switch/Vita] Retroarch sometimes crashes when loading content while vice core is loaded

### ISSUE THREAD

**Issue by rsn8887** [libretro/vice-libretro#34]
I can load the vice core, then load content just fine. But if I then try to load some other content into the vice core, then Retroarch crashes. Tested on Vita.

**Comment by sonninnos** [comment]
Is this still an issue? Works for me on Win64.

**Comment by rsn8887** [comment]
It has always been an issue and still is on Vita and Switch. It might not be vice related it happens on other cores too. It doesn’t happen every time either, only sometimes.

**Comment by rsn8887** [comment]
I verified this is an issue with all cores on Switch, not just Vice.

**Comment by rsn8887** [comment]
This is a general issue of Retroarch on Switch and Vita, so I made an issue there: https://github.com/libretro/RetroArch/issues/9236

**Comment by rsn8887** [comment]
This issue only affects static builds like Vita/Switch. It comes about because the core uses a lot of static variables that are not correctly reset unless the core is loaded and started fresh. Especially, several pointers are freed during deinit but not set to NULL. They are then again freed on init, when the main function is executed.

Loading from playlist and loading and starting the core from a blank sleight should work fine, but loading content while the core is already running does not work and ha never worked on these platforms.

**Comment by rsn8887** [comment]
I fixed this in b1b52f0
