### ISSUE TITLE
Launching file crashes RetroArch on M1 Macs

### ISSUE THREAD

**Issue by ToniMaroni** [libretro/vice-libretro#340]
Opening a file from the Commodore 64 file-list crashes RetroArch immediately; all other cores work so far. 

I tried the latest stable and the latest nightly RA releases and all Vice cores. M1 MacBook, macOS 11.1. 

Maybe there's something I could try? Thanks! 

[RetroArch_2020-12-24-033309_MacBook-Pro.txt](https://github.com/libretro/vice-libretro/files/5743085/RetroArch_2020-12-24-033309_MacBook-Pro.txt)

**Comment by sonninnos** [comment]
Is the core version the most recent? A related thing was fixed just a few days ago.

**Comment by ToniMaroni** [comment]
Yes, just went ahead and updated _everything_ anyway. RA unexpectedly quit again. 

I hope I'm not missing anything obvious  … filenames can't have spaces or something similar. Thanks for your quick reply sonninnos.

**Comment by sonninnos** [comment]
Updated as in compiled manually? Because it is not certain that the buildbot is offering actually new cores. Check out the commit version in the bottom left after loading the core.

**Comment by ToniMaroni** [comment]
Oh no, just used the RetroArch updater. I've "1.9.0 - VICE x64 (3.3 e1e4bdd)". 

So there might be help on the way; I'd rather wait a bit before installing Xcode myself. Thanks again friend.

**Comment by sonninnos** [comment]
Aye, no wonder then. Let's see what happens after the buildbot monkeys get the new bot up and running. Hopefully the issue is already sorted out.

**Comment by ToniMaroni** [comment]
Good news! Else you'll hear from me again; thank you so much sonninnos, you're the best.
