### ISSUE TITLE
[Doc,Monitor] data_type isn't defined anywhere

### ISSUE THREAD

**Issue by Michaelangel007** [libretro/vice-libretro#351]
In section 12.3 Memory Commands of the manual the following monitor commands are [listed](https://github.com/libretro/vice-libretro/blob/master/vice/doc/vice.texi#L15636-L15637):

```
mem [<data_type>] [<address_opt_range>]
m   [<data_type>] [<address_opt_range>]

memchar [<data_type>] [<address_opt_range>]
mc      [<data_type>] [<address_opt_range>]

memsprite [<data_type>] [<address_opt_range>]
ms        [<data_type>] [<address_opt_range>]
```

The problem is that `<data_type>` is _only_ listed in these 6 locations and _not actually defined anywhere else._ 

The command `memmapsave` lists `<format>` and defines it as (0 = BMP, etc.), but the commands with `<data_type>` don't clarify this optional argument.  I would have also expected it to be listed in Section 12.1 Terminology but alas it is not.

Can a user specify byte, int16, int32, float32 output? Or does this refer to hex, binary, decimal, octal output type? How does a user even know what the valid options are in the first place without resorting to looking at the [implementation](https://github.com/libretro/vice-libretro/blob/b005824c53f7687e59b3029f9853348dfb8261fa/vice/src/monitor/mon_memory.c#L251) ?

Without examples, which sadly there aren't any, a user is left guessing in the dark what `<data_type>` refers to.

Also, shouldn't the manual call this `<radix_type>` to match the usage of [t_radixtype](https://github.com/libretro/vice-libretro/blob/b005824c53f7687e59b3029f9853348dfb8261fa/vice/src/monitor/montypes.h#L134) and of the [command](https://github.com/libretro/vice-libretro/blob/b005824c53f7687e59b3029f9853348dfb8261fa/vice/src/monitor/mon_parse.y#L343) ?

**Comment by sonninnos** [comment]
Hmm, this does not really concern this repo, since it has nothing to do with official VICE devs and documents, and also because monitor is removed from the core due to keeping the size smaller.

It can be pretty easily put back, but it still can't be used without adding some core options and hotkeys for triggering it.

**Comment by Michaelangel007** [comment]
Thanks for the feedback.  I'll log the bug upstream.
