### ISSUE TITLE
Vice x64 speed up when using playlist (Switch)

### ISSUE THREAD

**Issue by cucholix** [libretro/vice-libretro#360]
https://user-images.githubusercontent.com/16081693/110248627-dbff8780-7f50-11eb-841d-28cda6ac538c.mp4

On Switch C64 games will run around x5 speed when launched from playlist, if the game is loaded through content it runs at normal speed. To fix it you need go back to the menu and enter to the game again.

https://i.imgur.com/wYMWE0y.mp4

**Comment by cucholix** [comment]
Here's the bisect
```
ff97418838139d70ca9ff6bb8b6f4c717c66181e Dec 20, 2020 ok
99021ee9a2536ab2b9be9eaa36eb086a08003935 Dec 21, 2020 won't compile
feb1b88775f1186803c590f1cda5e64779116b1d Dec 23, 2020 won't compile
c2e26f7b2cc085927f67b5686e1563e2da6a0ca6 Dec 27, 2020 won't compile
8dc6e7e3a6bc4c884544cdb5ba8521930ccd52bb Dec 28, 2020 won't complie
e9055d580573036c2476da3832a673165675bc66 Dec 31, 2020 playlist bug
```
ff97418838139d70ca9ff6bb8b6f4c717c66181e was the last one where the playlists were working correctly

**Comment by sonninnos** [comment]
Very much looks like something that needs fixing in the frontend then.

The change in the last listed commit changes audio to stereo and also to use `audio_batch_cb` instead `audio_cb`. Sure we could try confirming that by forcing Switch to use the previous audio callback.

**Comment by sonninnos** [comment]
Any difference now?

**Comment by cucholix** [comment]
Nope, the issue persists in latest build x64 fast

**Comment by sonninnos** [comment]
How about now with the latest memoryleak-begone operations?

**Comment by cucholix** [comment]
It’s still run too fast

**Comment by snoofly** [comment]
i’ve noticed this issue even when simply loading a single rom via load content with recent builds
Didn’t notice it a few weeks ago.
Once game is running, if I go back to the retroarch menu and then Resume all is fine.

**Comment by sonninnos** [comment]
Might be worth testing if anything is changed now.

**Comment by cucholix** [comment]
It’s fixed now

**Comment by sonninnos** [comment]
Excellent, I'll close this then.
