### ISSUE TITLE
vic20 Libretro lr-vice > linux Raspberry not work

### ISSUE THREAD

**Issue by jimizanei** [libretro/vice-libretro#365]
no game can be launched...black screen and again on menu games.
on log directory this :
[INFO] [CORE]: Loading dynamic libretro core from: “/usr/lib/libretro/vice_xvic_libretro.so”
[ERROR] Failed to open libretro core: “/usr/lib/libretro/vice_xvic_libretro.so”
Error(s): /usr/lib/libretro/vice_xvic_libretro.so: wrong ELF class: ELFCLASS32
[INFO] Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [CORE]: Unloading core symbols..
2021-03-21 14:31:31 INFO (emulatorlauncher.py:308):<module>: Exiting configgen with status 1

bad only with vic20   , c64 no problems.

**Comment by sonninnos** [comment]
Pretty sure that error `wrong ELF class: ELFCLASS32` has nothing to do with the code over here and thus can not be fixed with code. Thus I'll be closing.

Did you build it yourself or copied pre-built? If first, remember to do `make clean` after each `EMUTYPE=x` and if second, remember to copy the correct platform & architecture.

**Comment by jimizanei** [comment]
this can br replicated also on new installation , retropie , and install lr-vice binary or form source...  and never work  , c64 yes...
on pi4....   vice work, no problem , also with vic20...LR_VICE not!

**Comment by sonninnos** [comment]
Please redirect the problem to RetroPie then, as this repo has no affiliation with them.

I have a RPi2 and have noticed that RetroPie has only one core available, which by default will be `x64`. Every other VICE core needs to be built separately, as one core handles only one system. So if you are trying to launch xvic via command-line shenanigans, it is not going to work.

It can be built with `make EMUTYPE=xvic`. I just tried with RPi2 and at least with adding `platform=armv` it worked. Also the core over here launched fine: http://buildbot.libretro.com/nightly/linux/armv7-neon-hf/latest/
