### ISSUE TITLE
Cannot select a C128 or C64SCPU version from Options

### ISSUE THREAD

**Issue by JeffHanna** [libretro/vice-libretro#371]
I have all of the correct and MD5 matching JiffyDOS binary files in system\vice and I have the Super CPU 2.04 binary file in system\vice\SCPU64, yet neither a C128 nor a C64SCPU option is available under the Retroarch Options\Model list for vice-libretro. No C128 or SCPU specific options appear under the Options menu in Retroarch, either.

system\vice\
JiffyDOS_1541-II.bin
JiffyDOS_1571_repl310654.bin
JiffyDOS_1581.bin
JiffyDOS_C64.bin
JiffyDOS_C128.bin

system\vice\SCPU64\
scpu-dos-2.04.bin

**Comment by sonninnos** [comment]
There is no one VICE core that has all available machines. For C128 you need `vice_x128_libretro.dll/so` and for SCPU `vice_xscpu64_libretro.dll/so`.

**Comment by JeffHanna** [comment]
Thank you. Sorry for the confusion.
