### ISSUE TITLE
c64-libretro core wii

### ISSUE THREAD

**Issue by Steph71** [libretro/vice-libretro#372]
Hi,

has this ever been built for the nintendo wii console ?

Best Regards

**Comment by twinaphex** [comment]
It should be included in the nightlies, so you tell us I guess?

**Comment by Steph71** [comment]
ah, stupid me, binary is indeed in the retroarch binary distribution ... also in stable.
however trying to load the core on my wii crashes retroarch ....
I will try other cores and close this, in case they also crash ... as then it is probably not related to the core itself ....

**Comment by sonninnos** [comment]
Closing this due to one issue being enough: https://github.com/libretro/vice-libretro/issues/373
