### ISSUE TITLE
[SCPU64] Add support for CMD FD-2000 and CMD FD-4000 drives

### ISSUE THREAD

**Issue by Flupper** [libretro/vice-libretro#374]
Is it possible to add FD-2000 and FD-4000 drive support like standalone VICE has ?

Metal Dust greatly benefits from this if run from 2 disk version (d2m format for CMD FD-2000).
Even from a self-made 1 disked version without any disk-swapping required while playing (d4m format for CMD FD-4000).
(same load parameters as FD-2000 version in options)

The required drive roms in question is:
CMD FD-2000 DOS V1.40 CS 33CC6F.bin
md5: 3019d6d5890c6054674323bac1a8ab2e

CMD FD-4000 DOS V1.40 FD-350022.bin
md5: 9339ebfcb84d168856a50f869596a807

**Comment by sonninnos** [comment]
It seems to be working just fine already.

I made a D4M disk with CMD partition, copied Metal Dust to it, copied `drive4000` to `system/vice/SCPU64` and launched the D4M. "True Drive Emulation" needs to be turned off and kernal needs to be "Internal" though.

**Comment by Flupper** [comment]
Ahh, indeed it does work.
FD-4000 and standard kernal loader in Metal Dust settings + d4m image = virtually no loading at all, it just flies.
