### ISSUE TITLE
Datasette volume not changeable ?

### ISSUE THREAD

**Issue by zzedmore** [libretro/vice-libretro#378]
Hi, I tried the new Datasette sound (on a Pi 400) but the percentage you choose doesn't seem to make any difference. 5% sounds loud, and the same as 40% etc. I also couldn't hear any loading music while it was switched on.

**Comment by sonninnos** [comment]
It works perfectly fine, with loading music and all, with ReSID, but apparently not with FastSID. FastSID is not even available by default in the standalone anymore, which means that this will never be fixed here either. 

Which means I'll be closing this. I'm pretty sure RPis have enough juice for proper ReSID quality.

**Comment by zzedmore** [comment]
My Pi is already set to ReSID and 'Resampling' audio. The Datasette Sound is just one loud volume and cannot be lowered or raised.  Also happens with x64sc.

What's weird is that if I use FastSID then I get no Datasette sound, but when the loading music starts playing I can hear the datasette sound or some white noise ? If I try to raise or lower the volume in the core options then go back to emulation it crashes.

**Comment by sonninnos** [comment]
Hmm, I just tried with RPi2 and indeed something is weird. 5% is full blast, 10% less loud, 15% less loud, 20% full blast, etc, which makes no sense.. and indeed FastSID just crashes. Something funky with the volume value range then.

I don't think we can do much about FastSID, but volume surely can't act that way.

**Comment by sonninnos** [comment]
Phew, finally found the reason for the randomness: The classic ARM default unsigned vs signed char when not explicitly stated. So simply forcing this variable to signed did the trick.

```diff
-static char datasette_square_sign = 1;
+static signed char datasette_square_sign = 1;
```

I also fixed the audio mixing so that SID quality stays the same when Datasette sound is enabled, and added a bonus option for muting SID while the tape is playing at max volume. Will be included in the next batch.

**Comment by zzedmore** [comment]
Nice one!
