### ISSUE TITLE
Gmod2 support

### ISSUE THREAD

**Issue by NascentTech** [libretro/vice-libretro#380]
gmod2 catridges do not appear to read/save data to the associated eeprom image.

Updated the vicerc file to turn on the update flag for gmod2 and add in a path and filename for the eeprom file.  Verified that the configuration is set to read the vicerc file. Tested a few different catridges, but this does not appear to work at this time.

vicerc changes
GMod2EEPROMImage="_full path to eeprom/eeprom_" ### No description
GMod2FlashWrite=1 ### No description
GMod2EEPROMRW=1 ### No description

log shows the following error
[libretro ERROR] Filesystem Image Probe: Import GCR: Unknown GCR image version 82.

**Comment by sonninnos** [comment]
Few things come to mind:
1. Are those settings after the wanted machine block?
    - `[C64]` for fast x64, and `[C64SC]` for accurate, for example? Just like in standalone config file.
2. Does verbose log say `Reading configuration file 'x'`?

**Comment by NascentTech** [comment]
Thank you for the list as this helps to focus the search.  I was able to find the cause of the issue.

In the log file I found
[libretro ERROR] Cannot assign value '"D:\RetroArch\saves\eeprom.bin" ### No description' to resource 'GMod2EEPROMImage'.

So, it appears that it is attempting to assign the full value of the line from vicerc as the path including _'### No description'_ which should be excluded as a comment.

So, editing vicerc
GMod2EEPROMImage="D:\RetroArch\saves\eeprom.bin" ### No description
changes to 
GMod2EEPROMImage="D:\RetroArch\saves\eeprom.bin"
and now it works correctly.

This will probably be the same for any similar entries in vicerc.

**Comment by sonninnos** [comment]
Nice. I actually had the removal of the extra ### stuff in my suggestion list initially, but wasn't sure if it would matter. I guess we can close this then.

**Comment by NascentTech** [comment]
The issue is resolved for me, but perhaps it is best to have at least one change prior to closing.

1. Change code to ignore the comments or anything outside of the quotations.
2. Remove the descriptive comments from the file.
3. Update documentation concerting vicerc, editing it, and the need to remove the descriptive comments.

Otherwise, this will be a recurring frustration for others.

**Comment by sonninnos** [comment]
1. VICE is responsible for reading the file, so that will not be changed
2. This core is responsible for the dumps and the comments in the dumps (standalone does not even dump), but without them it is much harder for the user (even though not all options have descriptions), so that won't be changed either
3. That can be added somewhere I guess

**Comment by sonninnos** [comment]
1. was simple to implement after all, and I also added logging for successful config line reads.
