### ISSUE TITLE
PAL colour blending demo

### ISSUE THREAD

**Issue by IAmBoring** [libretro/vice-libretro#383]
I'm using the x64 fast core and tried this program here running in PAL mode
http://www.larshaugseth.com/c64/colmix.html

Middle squares are the same color whereas they should be blended somewhat differently. I've seen this "scanline trick" in several games. What settings should I use to simulate this effect? Or do I need to use a shader?

**Comment by sonninnos** [comment]
Hmm, at the moment shaders are the only way, because the CRT render path in standalone is skipped here.

But it looks like it is doing a good job with that test, so maybe we should allow enabling it.
