### ISSUE TITLE
.m3u and manual disc swaping (from Disc Control menu) not working.

### ISSUE THREAD

**Issue by xttx** [libretro/vice-libretro#392]
Tested with retroarch 1.9.0 and 1.9.3 (windows version).
Tested with xvic and x64sc cores.
all settings (both RA and core) was reseted to defaults.

The core version from 04.01.2021 works fine.
The core version from 29.03.2021 and up to most recent version - not working.

When loading .m3u file, the first image is autostarted as expected. But in RetroArch Disc Control menu. the "Current Disk Index" label, just says "No disk selected", with no way to change it. Trying to Eject/Insert disk, just pop up RA message: "Failed to eject/close virtual disk tray".
Tried to save .m3u using different encodings (ascii, UTF with BOM, UTF without BOM) - no change.
Tried to use different paths in .m3u (relative, absolute, absolute in quotes) - the latter does not even load the first file, otherwise no change.

When trying to add disks manually, using Disc Control/Load New Disk, the disks can be properly inserted and ejected. But only the first one is actually loaded, whatever disk index I choose.
e.g. start core without content
- Disc Control/Load New Disk (Disk A)
- Disc Control/Load New Disk (Disk B)
- Hit "Insert Disk" and reset the core (the disk A will be autostarted)
- Go to Disc Control, then eject disk, change disk to the second one and insert the new disk
- Reset the core - the disk A will be autostarted again

[retroarch__2021_05_23__11_57_36.log](https://github.com/libretro/vice-libretro/files/6527820/retroarch__2021_05_23__11_57_36.log)

**Comment by sonninnos** [comment]
I don't have any such issues with x64(sc) neither with manual or auto generated M3Us, but indeed something with disks seems to be off in xvic..

And I'm pretty sure quotes do not belong in M3Us.

The disk being the first one after RA reset is by design. Starting from some other disk works by using the internal reset.

**Comment by xttx** [comment]
Retested .m3u with all available VICE based cores. Looks like I messed up - only xvic seems to be affected. I'm sorry for that :(.
