### ISSUE TITLE
Rewind not working 

### ISSUE THREAD

**Issue by eadmaster** [libretro/vice-libretro#394]
I obviously have [Rewind Support](https://www.lakka.tv/doc/Rewind/) enabled in its menu with its default settings.
Savestates and fast forward are working fine, but i cannot rewind in any game.

**Comment by sonninnos** [comment]
Working fine here on Windows.

**Comment by eadmaster** [comment]
> but no problem when enabled afterwards.

ok, i am using this as a workaround atm.

**Comment by sonninnos** [comment]
No need for long, since I got it fixed, and pushing soon.
