### ISSUE TITLE
[VITA] Strange hissing/crackling issue with the sound

### ISSUE THREAD

**Issue by 16mpx** [libretro/vice-libretro#402]
Hi,

I have not updated the retroarch for a while and when I did it lately, I am having a strange hissing and crackling issue with the sound with vice c64 core for Vita. Before, it was version 3.3 and the sound was ok, and now it is version 3.5 built 8b5df00 and sound has the defined issue. Any parameters I can fine tune in the sound settings to fix this ?

**Comment by sonninnos** [comment]
Please provide a recording of it, since it isn't happening on any hardware I have.

**Comment by 16mpx** [comment]
Please check the below link for the sample recording.

https://youtu.be/O34JjdDFRpg

I am also attaching a verbose log with a fresh opt file.

[retroarch__2021_07_17__21_53_09.log](https://github.com/libretro/vice-libretro/files/6835239/retroarch__2021_07_17__21_53_09.log)

**Comment by sonninnos** [comment]
Sure sounds weird. And it still manages to deliver full framerate? Same with NTSC?

Not very likely that some parts of the emulation became more accurate and demanding during that time in a way that a small overclock would cover it, so perhaps something is up with the revised audio buffer..

Does the sound sample rate core option and/or trying FastSID make any difference?

**Comment by 16mpx** [comment]
Nothing wrong with the framerate, and same with NTSC.

Unfortunately no difference with the FastSID engine and changing (lowering) sound sample rate also has no positive effect.

Does sound handling differs between the versions 3.3 and 3.5 ? Maybe this difference can cause the issue..

**Comment by sonninnos** [comment]
Yes, the codebase had big changes and also the core added support for multiple SIDs.

The output used to be always mono, but currently it is always stereo. Adding another SID will put the first one to left channel and second to right channel. So does the "SID Extra" option do anything else except that there?

**Comment by 16mpx** [comment]
I have tried all available addresses in the "SID Extra" options menu but the effect is only to put sound to the left channel as you have mentioned, nothing changed with the sound quality unfortunately.

**Comment by sonninnos** [comment]
I pushed a tiny change which probably won't do anything, as it did not make it any better or worse in Windows or RPi2.

**Comment by 16mpx** [comment]
I have tried it and you are right, sound is still same.

I you agree, I can close the issue for now.

**Comment by sonninnos** [comment]
No closing until it is solved.

**Comment by sonninnos** [comment]
Sure this is the only core that does this?

**Comment by 16mpx** [comment]
There are other cores (like libretro-uae) that suffers because of the ps vita's performance constraints but as I mentioned earlier, this core has perfect sound before even if I underclocked vita cpu to 333 mhz but now it suffers.

**Comment by sonninnos** [comment]
It must be related to this one then: https://github.com/libretro/vice-libretro/issues/411

**Comment by sonninnos** [comment]
Have you tried other resampler settings in the frontend, most importantly quality to `normal` instead of default `lower`?

**Comment by 16mpx** [comment]
I have tried the latest build (81e9837) just now and audio is perfectly fine issue is gone.

**Comment by sonninnos** [comment]
Great! Maybe it was the audio buffer size adjustment then.
