### ISSUE TITLE
Update to Vice 3.1

### ISSUE THREAD

**Issue by hiddenasbestos** [libretro/vice-libretro#41]
Simple request to update core to version 3.1 of Vice.

**Comment by 5schatten** [comment]
Well then straight update to 3.2 -> http://vice-emu.sourceforge.net/NEWS

**Comment by escalade** [comment]
I don't think there's much changes regarding accuracy and core emulation engine in Vice these days.

**Comment by rsn8887** [comment]
I think the sid emulation with reSID sound driver has been much improved recently, so it should be good to update the core.

**Comment by escalade** [comment]
Does this core use/support reSID though?

**Comment by fuzzy76** [comment]
3.3 is out with some optimizations.

**Comment by rsn8887** [comment]
Yes this core supports resid

**Comment by rsn8887** [comment]
Another reason to update: I think resid emulation has become much faster at some point recently. For example, in 3.2 it is much faster than in 3.0, it runs even on a PSP without slowdown, using 3.2. So updating the core should also help with that resid slowdown that is present currently on slower machines.

**Comment by rsn8887** [comment]
Fixed by yesterdays update to 3.3
