### ISSUE TITLE
VSF snapshots saved using SDLVICE don't load anymore

### ISSUE THREAD

**Issue by fastpop72** [libretro/vice-libretro#420]
As stated here the problem was solved last year but now VSF files doesn't load anymore in Retroarch / Libretro-vice core.

https://github.com/libretro/vice-libretro/issues/213

**Comment by sonninnos** [comment]
Log should tell the reason.

**Comment by fastpop72** [comment]
@sonninnos Not very much... Only says "too old".

But it says an interesting statement about the Snapshot version. Why should expecting an old snapshot version in latest Vice?

[libretro INFO] AUTOSTART: Restoring snapshot.
[libretro ERROR] Snapshot version (2.0) not valid: expecting 1.1.
[libretro ERROR] Snapshot D:\SDL2VICE-3.5-win64-r40846\snapshot.vsf is incompatible (too old), Snapshot was created by VICE Version 3.5.0 (r40846).

**Comment by sonninnos** [comment]
Looks like later 3.5 versions have changed the snapshots yet again. This is core based on the stable 3.5.

And the same thing shall happen at 3.6.

**Comment by fastpop72** [comment]
So the only chance to use VSF files in RetroArch+lr-vice core is to create them with the stable SDL2-VICE 3.5 version?

Unfortunately only the GTK3 stable version is available.... no binaries for SDL2 stable version...  only nightly are available.

**Comment by sonninnos** [comment]
Yes. GTK/SDL should not matter though, since the GUI does not dictate internal operations, but could still be the case.

**Comment by fastpop72** [comment]
With VSF file just created with stable GTK or SDL version 3.5 gives this error in both cases...

[libretro ERROR] VIC-II: Snapshot was made with model 1 while the current model is 0.

**Comment by fastpop72** [comment]
@sonninnos I'd like to use Vice for creating VSF files because with integrated monitor and breakpoints i can create perfect freezes.

**Comment by sonninnos** [comment]
I don't know what is up. It accepted the file here when I created a snapshot with the same SDL2 3.5 version..

**Comment by fastpop72** [comment]
> Edit: Hmm, that error comes when VIC-II model is not the same, which should only be possible when other is C64 and other is C64C, since they use different chips, and standalone defaults to C64C, but this core defaults to C64.

GOTCHA!!! I must set the Vice machine to C64 instead C64C!!!!

@sonninnos  Many many many many thanks!!!!!

**Comment by sonninnos** [comment]
No problemo. Of course you can use whichever model you prefer.

I changed the default in this core to C64, because when I think of C64 I think of the original breadbox with the superior sound chip.

**Comment by fastpop72** [comment]
@sonninnos Anyway there are some problems on loading VSF...

Here's an attached VSF created with stable 3.5 (GTK3) working in Vice but crashing in RetroArch.

[beyond.zip](https://github.com/libretro/vice-libretro/files/7279566/beyond.zip)
.

**Comment by sonninnos** [comment]
The crash has nothing to do with VICE settings, but instead it was caused by the hack that I've added to the core, which stops saving EF cart data to the savestate. It not only saves a lot of space, but also allows saving save data to the cart after using savestates. Standalone will ignore all saves to the cart when using snapshots.

I was able to fix it so that both RA savestates and VSF work properly. And I also did the same for D64 disks, since those snapshots are also hacked to include only the file name instead of file data, in order to be able to switch multi-disk game disk index automatically when using M3U files.

Obviously that VSF approach is doomed when it comes to multi-disk games, but at least single disks should work now like normal.

Please test this if there are more issues: 
[vice_x64sc_libretro.zip](https://github.com/libretro/vice-libretro/files/7280836/vice_x64sc_libretro.zip)

**Comment by fastpop72** [comment]
> The crash has nothing to do with VICE settings, but instead it was caused by the hack that I've added to the core, which stops saving EF cart data to the savestate. It not only saves a lot of space, but also allows saving save data to the cart after using savestates. Standalone will ignore all saves to the cart when using snapshots.
> 
> I was able to fix it so that both RA savestates and VSF work properly. And I also did the same for D64 disks, since those snapshots are also hacked to include only the file name instead of file data, in order to be able to switch multi-disk game disk index automatically when using M3U files.
> 
> Obviously that VSF approach is doomed when it comes to multi-disk games, but at least single disks should work now like normal.
> 
> Please test this if there are more issues: [vice_x64sc_libretro.zip](https://github.com/libretro/vice-libretro/files/7280948/vice_x64sc_libretro.zip)
> 
> Edit: Derp, found a crash, will fix shortly. Edit2: ZIP updated.

It works properly now, with both VSF type of files (roms or disc attached). 

These fixes will be commited to master?

**Comment by sonninnos** [comment]
Excellent. I'll do my usual test rounds first and then merge soonish.
