### ISSUE TITLE
Autoload Warp using Tapes (Loading Music)

### ISSUE THREAD

**Issue by zzedmore** [libretro/vice-libretro#422]
You have an excellent feature that Auto Warps and stops when sound is played. Can you add this for Tapes too ? So that it stops warping when loading music is played.

Although it's probably not recommended to have this feature on when playing demos (Disk), I have noticed that it sometimes warps between sound notes. It's detecting a small amount of silence then warping. I noticed it on the 'Star Wars' demo by Censor Design.

**Comment by sonninnos** [comment]
Auto warp has currently nothing to do with sound with any format. It only reacts to drive/tape usage. But not for long.
