### ISSUE TITLE
M3U with disks using a subfolder entry

### ISSUE THREAD

**Issue by theflyingape** [libretro/vice-libretro#435]
FWIIW, when constructing a content directory with only m3u files that have subfolders to disk images will only work properly AFTER a restart.  I suspect it's because it needs to copy the images over to a working TEMP directory to cache on FIRST Start, and something is "broken" there?  Because after pressing the End key to RESTART it in place, it must skip that caching step and all boots fine.

An example C64 M3U:
```
gamedisks/Adventure Construction Set (USA, Europe) (Side 1).nib|Right side up
gamedisks/Adventure Construction Set (USA, Europe) (Side 2).nib|Upside down
savedisks/Adventure Construction Set (USA, Europe).d64|My Game Floppy
```
... if I move the disk image files in the same folder as m3u file and remove the path to gamedisks/ and savedisks/ above, it boots up fine at first start -- no need for a manual restart.

**Comment by sonninnos** [comment]
NIBs are not accessed directly, as in they are converted to G64 first in the same TEMP where ZIPs are extracted. So it should be fine if you copy the converted files from the TEMP while it is running and replace those NIBs.

**Comment by theflyingape** [comment]
I am definitely mistaken! Somehow, the core global option kicked in with a Global Work Disk on Device #9 -- something I enjoy having set globally for the VIC 20 core, but not C64.

That's another "issue", because even if #9 were set in this manner, the media eject/insert handling is for Device #8.

So, without any Global Work Disk option set, I can use subfolders set in the m3u playlist.  Onward.

**Comment by sonninnos** [comment]
That definitely needs fixing then, since work disk in unit 9 should not affect the main disk unit 8 in any way.

And is this with the current version, since I did some changes regarding work disk when adding the directory option, so did that break it or was it broken already?

**Comment by sonninnos** [comment]
Please test if the work disk option still causes issues with the current commit.
