### ISSUE TITLE
copy home into browser->directory for WIN32?

### ISSUE THREAD

**Issue by runvnc** [libretro/vice-libretro#44]
It looks like file_browser_init in `filebrowser.c` fails to copy the `home` string into `browser->directory` before calling `dir_list` but only has this problem on WIN32.

**Comment by hiddenasbestos** [comment]
I think the #endif on line 182 of filebrowser.c should be moved above the strcpy block, directly after the getpwuid. I moved it up there but didn't get much of a different result so I guess it needs further investigation.

**Comment by sonninnos** [comment]
That Nuklear filebrowser is now removed thanks to the m3u feature.
