### ISSUE TITLE
Winvice 3.5 issue

### ISSUE THREAD

**Issue by Forest31** [libretro/vice-libretro#448]
![2022-01-06 (1)](https://user-images.githubusercontent.com/92609935/148448747-7c3f72c8-cc36-4aa8-a46e-ba3ac4b0d437.png)
Apologies, I am new here
Ever since I downloaded WinVice 3.5, xpet refuses to run and scpu64 is slower to show up. Is this a build issue? I double click and nothing happens
thanks for any help you can give

**Comment by sonninnos** [comment]
You are totally in the wrong place. This is not WinVICE and can do nothing about any issues it has.

**Comment by Forest31** [comment]
> You are totally in the wrong place. This is not WinVICE and can do nothing about any issues it has.
> 
> But those particular issues are fixed in this core, and AFAIK they are also fixed in 3.6 standalone.

where do i go then? I'm still new to the site

**Comment by Forest31** [comment]
thanks for the help :)
