### ISSUE TITLE
Files not autolaunching if special characters exist in path

### ISSUE THREAD

**Issue by vagrant-17** [libretro/vice-libretro#453]
eg. I have a .prg file I'm trying to launch from this location;
"01. Fancy Rats - Stary Licheń Song/stary_lichen_song.prg"

It fails with unknown filetype error in log.
When I remove the special character from path;
"01. Fancy Rats - Stary Lichen Song/stary_lichen_song.prg"
it launches fine.

I have special characters enabled in frontend options.

**Comment by sonninnos** [comment]
Weird, since D64 files do work from such paths, but PRGs don't. Of course when I last time fixed non-ascii paths, I did not test PRGs..

**Comment by vagrant-17** [comment]
Strange! I can't confirm if PRGs have ever worked from such paths, it could be the first time I've tried to run such case

**Comment by sonninnos** [comment]
I narrowed it down to the VFS addition, as in it works if VFS is disabled (by building with `make NO_LIBRETRO_VFS=1`)..

Indeed odd that no other file format does the same `stat` checking, but I'll sort it out shortly.
