### ISSUE TITLE
Plus/4 disk support broken

### ISSUE THREAD

**Issue by Jamirus238** [libretro/vice-libretro#455]
Tested a couple of d64 disk images (Winter/Summer Events, Gunfright), all return a file not found error, while working correctly with standalone Vice.

**Comment by sonninnos** [comment]
For some reason D81 disks work, but apparently not D64s..

**Comment by sonninnos** [comment]
Odd. Forcing the default 1551 drive type to 1541 fixes the issue. Standalone does work with 1551 though, but here it does not even after updating the embedded 1551 drive ROM, which has some differences.

So I guess I'll go with the band-aid for now..
