### ISSUE TITLE
Autoload not working when zipped file load via Browse Archive option

### ISSUE THREAD

**Issue by ImJezze** [libretro/vice-libretro#466]
The autoload feature does not work when a zipped file (.d64, .t64, etc.) is selected via the Browse Archive option. It seems the disk/tabe is not even attached, because I cannot use a command like LOAD"*",8,1 to run it.

However, it is possible to autoload the .zip file using the Load Archive option instead. Then the archive is extracted to the TEMP folder and loaded from there.

**Comment by sonninnos** [comment]
Whoops, looks like it was broken by a crash fix aimed at linux platforms regarding launching content paths that are not valid. Fixed in the next batch.
