### ISSUE TITLE
C128 keyboard

### ISSUE THREAD

**Issue by Vweber73** [libretro/vice-libretro#468]
Hi,

Emulator works great, the addition of REU was very good for GEOS, thanks !
Just one thing that bugs me, the C128 virtual keyboard is not complete, some of the extra keys (compared to C64) are missing, F5 and F6, for instance, have the same behaviour (HELP) whereas they shouldn't...

Is there any plan to make the keyboard 100% like the original ?

Many thanks and best regards

**Comment by Vweber73** [comment]
Hi,
Excellent, many thanks !
Are the functions keys fixed too ? Currently F5 and F6 both trigger "HELP", for instance...
Best regards

**Comment by sonninnos** [comment]
Of course.

**Comment by Vweber73** [comment]
Excellent, thanks !

**Comment by Vweber73** [comment]
Hi,

I could not see this on the new core, has it not been implemented yet, or is there something to activate it ?

Many thanks and best regards

**Comment by sonninnos** [comment]
Of course there is nothing needed to activate it once it is in. I had to improve a bunch of things while I was at it, but I'll try to push today.

**Comment by Vweber73** [comment]
Excellent, thanks ! 
Well, Retroarch can be so complicated, you never know, maybe it was needed to load a separate keypad... I preferred to make sure :)
What are the other improvements ?
Many thanks and best regards
