### ISSUE TITLE
Something funky with auto Warp

### ISSUE THREAD

**Issue by zzedmore** [libretro/vice-libretro#475]
I'll double check tomorrow but I just tried loading a few .TAP files with AutoLoadWarp ON but doesn't seem to make any difference ?

**Comment by sonninnos** [comment]
Not only that but the tape counter is broken in statusbar (which autowarp is relying on), because now floppy drive is enabled even when it is not booted from, and using both tapes and drives at the same time was never planned. Will find a solution ASAP.

**Comment by zzedmore** [comment]
> Not only that but the tape counter is broken in statusbar

Ah, I wondered why I had to leave the virtual keyboard on to see the tape counter ! I thought you may have removed it from the status bar for some reason.

**Comment by zzedmore** [comment]
Thankyou.
