### ISSUE TITLE
VICE XVIC prg games dont start. 

### ISSUE THREAD

**Issue by apison** [libretro/vice-libretro#476]
Bye, i'm using vice for vic20, and it used to work correctly with prg file. With the latest versions it seems to have problems loading prg files, when i try to load them, vice load the basic screen and nothing happens. I've tried both android and win64 version, with zipped or unzipped prg files. Tap files are loaded correctly.

**Comment by apison** [comment]
The same prg files works with the standalone vice version.

**Comment by sonninnos** [comment]
Looks like it was caused by an autostart related backport some time ago, causing prgs to recognize and attach as carts instead..

**Comment by apison** [comment]
Thank you sonninnos, so no solutions for now?

**Comment by sonninnos** [comment]
Will fix ASAP.

**Comment by apison** [comment]
Grat, thank you
