### ISSUE TITLE
JiffyDOS when emulating SX-64 isn't working

### ISSUE THREAD

**Issue by veganvelociraptor** [libretro/vice-libretro#479]
I can easily get this to work with native VICE, just by changing the ROM files in vicerc as per below. However, this doesn't work with the libretro core.

![vice-screen-2022100411234616](https://user-images.githubusercontent.com/29574272/193784147-72bef9c9-b114-4802-a533-7e2f8a03b2ef.png)

Just switching on JiffyDOS in the core options doesn't seem to do anything. I'm not even sure the core supports loading JiffyDOS_SX-64.bin as it's not listed as an optional component in the core info.

What I tried was to create a custom vicerc, just like the one I use for native VICE:

> [C64]
> KernalName="/run/media/mmcblk0p1/steamapps/common/RetroArch/system/vice/JiffyDOS_SX-64.bin"
> DosName1541="/run/media/mmcblk0p1/steamapps/common/RetroArch/system/vice/JiffyDOS_1541.bin"
> DosName1541ii="/run/media/mmcblk0p1/steamapps/common/RetroArch/system/vice/JiffyDOS_1541-II.bin"
> DosName1571="/run/media/mmcblk0p1/steamapps/common/RetroArch/system/vice/JiffyDOS_1571_repl310654.bin"
> DosName1581="/run/media/mmcblk0p1/steamapps/common/RetroArch/system/vice/JiffyDOS_1581.bin"

This didn't work either. I also tried replacing the JiffyDOS_C64.bin file with JiffyDOS_SX-64.bin, which made no difference:
![RetroArch_20221004_112517](https://user-images.githubusercontent.com/29574272/193784978-6099bff6-750c-4105-9b75-02d2cc4eff58.gif)

I tried all this with different combinations of SX-64 PAL/NTSC and JiffyDOS on/off in the core options. Is it possible to actually achieve what I'm trying to do here, or is the combination of SX-64 and JiffyDOS not implemented at all in the libretro core?

**Comment by sonninnos** [comment]
It is not thought out at all, because why is it needed really?

**Comment by sonninnos** [comment]
Ok, I got this sorted. I also thought about adding it for VIC-20 too because why not, but noticed that it makes the screen very badly misaligned when using PAL, so maybe it is not worth the hassle..
