### ISSUE TITLE
Gzipped d71 (d7z) files don't work

### ISSUE THREAD

**Issue by veganvelociraptor** [libretro/vice-libretro#480]
This happens when attempting to autoload a gzipped d71 file with the d7z extension:

> LOAD"(NULL)",8,1
> 
> SEARCHING FOR (NULL)
> ?FILE NOT FOUND  ERROR
> READY.
> RUN:
> 
> READY.

This doesn't happen with gzipped d64 (d6z) or d81 (d8z) files. I've tried the native VICE emulator and they work perfectly fine in VICE.

**Comment by sonninnos** [comment]
Yep, for some reason it is treating it like a FS directory, yet `.d71.gz` works. Should be simple to sort out.
