### ISSUE TITLE
x128 core: JiffyDOS not disabled when autoloading tap/t64 files

### ISSUE THREAD

**Issue by veganvelociraptor** [libretro/vice-libretro#486]
With all the x64 cores, JiffyDOS is automatically disabled when autoloading tap/t64 files (as it should be, since the tape routines are overwritten by JiffyDOS in the kernal). This includes the x128 core when running in GO64 mode. However, this is not the case when running in native C128 mode, as per this screenshot below:
![Tomcat-230121-140410](https://user-images.githubusercontent.com/29574272/213868156-80481f7d-5cc1-46e0-8094-0d2be481989f.png)

And this is how it looks when I switch on GO64 mode in the core options:
![Tomcat-230121-140442](https://user-images.githubusercontent.com/29574272/213868174-e4d849aa-c8fb-4701-91a9-415d069709cc.png)

**Comment by sonninnos** [comment]
I got this sorted for the next 3.7 release. Maybe not worth the effort to do it for current version.
