### ISSUE TITLE
Keyboard/VKB and odd speed issue with game loaded from tap

### ISSUE THREAD

**Issue by thepixeladdict** [libretro/vice-libretro#489]
Hi,

I'm seeing an issue with Monty on the Run when autoloaded from a tap file (Monty on the Run (Zzap Sizzlers II Collection - Kixx).tap) that doesn't seem to exist when using a crt version of the game. The tap version once loaded appears to show the high scores scrolling much faster than they should on the title screen (warp isn't enabled and music and other elements appear to be at correct speed), and then when prompted to enter your name to record a high score, no input is recognised from either the virtual onscreen keyboard or using a physical keyboard (except for the space key). This all appears to work fine with the same setup when using a crt version of the game. It's like some kind of CIA issue but only exhibiting with the tap version of the game. The game can still be played via a joystick in port 2 as normal, but you can't get past the high score name entry part to start a second game.

I've tested the tap file with the full Windows 64-bit GTK3 3.7 release of VICE and the issue doesn't appear to exist there. Testing on a real C64C with the same tap file has no issue either.

My setup:
Windows 11 Pro 22H2
Retroarch 1.15.0
vice-libretro x64sc 3.7 0dfc133

**Comment by sonninnos** [comment]
Just as I suspected, the hack for skipping the start pause when the item is found from tape is malfunctioning again, making the key stay down. Simply pressing C= key once will fix it up for now.

**Comment by thepixeladdict** [comment]
Many thanks, I can confirm that workaround does indeed resolve the issue for both the abnormal speed on the title screen and keyboard input.

**Comment by sonninnos** [comment]
Indeed with that particular tape it never gets the state that tells it to release the key, but it does work with some other tapes like Rambo 2.. I either have to ditch the whole feature or try some other method of forcing the release after it has served its purpose.
