### ISSUE TITLE
Remove hardcoded binding: Controller R3 = Vice GUI

### ISSUE THREAD

**Issue by Gazdaman** [libretro/vice-libretro#49]
Remove hardcoded binding: Controller R3 = Vice GUI

Having the core GUI hard binded to R3 on the game controller causes several problems:

1. If you enter this GUI it quite often freezes the Game on exiting the GUI.
2. As it is mapped to R3, it causes problems if you use the L3+R3 combo to enter the RetroArch GUI.

Please remove this hard binding.
It offers no additional functionality as all settings are accessible in the RetroArch GUI.
It also introduces complications or problems as described above.

Using Android Vice x64 core 2018-04-20
Also tested and found the same issue on Windows x32 build

**Comment by rsn8887** [comment]
Fixed by PR #73
