### ISSUE TITLE
Geos 128 change of colors 

### ISSUE THREAD

**Issue by Vweber73** [libretro/vice-libretro#492]
Hi,
I used to launch GEOS 128 from the 1581 disk.
I hadn't done it a long time, several core updates happened in between, including the option to change the VDC memory (16 or 64kb).
I just tried again, and I was surprised to see that GEOS 128 doesn't boot in black and white anymore, but in quite horrible Yellow and blue colors. You can change the colors in the preferences, but the white is not as white as it used to be...
I don't remember doing anything back then that would warrant such colors. Is something in the emulation changes  can explain that?

Many thanks in advance, best regards

**Comment by sonninnos** [comment]
Hmm, something weird randomness with the "VDC Filter" option. Standalone looks gray always with enabled or not, here disabled is always gray, and yellow tint appears if enabled by selecting any blur specific variant first..

**Comment by Vweber73** [comment]
Many thanks again for your quick answer.
I disabled the VDC filter, booting was grey as before, great, then it turned yellow again, but this was because of the color preferences I had tuned in an attempt to fix it, I reverted and everything is back to normal!
Yet I guess this filter is useful, so a fix is needed?
Cheers

**Comment by sonninnos** [comment]
Ok, got it figured out. Also decided to fix the automatic cropping of VDC screens. Also have to fix the VKBD and do more testing, but looking good.

**Comment by Vweber73** [comment]
Excellent, thanks!
Fix the VKBD? in what way?

**Comment by sonninnos** [comment]
It is very much off when in the GEOS screen mode.

**Comment by Vweber73** [comment]
Here is what I got... How is it off? 
![Screenshot_20230827_003027_RetroArch (AArch64)](https://github.com/libretro/vice-libretro/assets/92450215/ce8fb07f-5038-47b3-a14f-07901d43b644)

**Comment by sonninnos** [comment]
It isn't using the available are properly like in every other mode.

**Comment by Vweber73** [comment]
Ah, vertically, yes, I see what you mean

**Comment by Vweber73** [comment]
Works absolutely great as advertised, now I have full screen GEOS 128, wonderful!
Many thanks again for your outstanding reactivity and efficiency.
Best regards
