### ISSUE TITLE
[Features Request] Update Vice to the latest version 3.8

### ISSUE THREAD

**Issue by KamiLordus** [libretro/vice-libretro#496]
Hi@sonninnos. I have a problem with the game Super Space Invaders (Domark). The game just doesn't work on Vice 3.7. I tested both the tap and g64 versions and the cpu jam error appears. Same problem on standalone vice 3.7. The bug was fixed after the release of Vice 3.7.1 (unfortunately I don't know which exactly version fixes this problem).
In the tested version 3.7.1 r44453 (lates 3 days ago) the problem no longer occurs.
Is it possible to switch to the latest version for vice core, or fix the bug in the current one?
I'm posting both the tap version and the g64 version for testing if needed.
[Super Space Invaders.zip](https://github.com/libretro/vice-libretro/files/12489780/Super.Space.Invaders.zip)

**Comment by sonninnos** [comment]
Not really a huge fan of adding changes between versions, especially since 3.8 is around the corner again, but if you help finding the commit that fixes it, I can include it.

**Comment by KamiLordus** [comment]
Unfortunately, in the reviewed versions from the latest to 3.7 there is nothing about cpu_jam or space invaders.
Alternatively, I will ask vice creators themselves, if they want to write back.
I hope version 3.8 will appear soon :)

**Comment by sonninnos** [comment]
Well "soon" is a relative term, but they tend to do christmas releases, and I tend to swiftly update the core after that. So we might want a quicker solution.

**Comment by KamiLordus** [comment]
I wrote a question to them. But after security via sourceforge.net I don't think they answer questions often :)
I'm also looking at closed and open bug reports on this page, but I don't see anything about it. Maybe it's called differently, or maybe it was fixed by the way.

**Comment by KamiLordus** [comment]
They wrote back that SSI version vice r44453 works fine. But I figured it out myself yesterday. So I started checking individual versions where the problem is and where not.
And I quickly discovered that in the basic version of 3.7.1 the game does not work properly. It's already in the next update r44342 the game is already working without a problem.
https://github.com/VICE-Team/svn-mirror/releases/tag/r44342

**Comment by sonninnos** [comment]
Hmm, r44342 can't surely be "next" from 3.7.1, since there is ~6 months of code between the dates..

**Comment by KamiLordus** [comment]
My mistake, I didn't notice that there is such a big gap between 3.7.1 and r44342. I don't see any earlier versions anywhere and probably the creators of vice themselves won't remember.
It remains to wait for 3.8

**Comment by KamiLordus** [comment]
Hi sonninnos. Vice version 3.8 has just been released. Will it be possible to transfer it to the retroarch platform?

**Comment by KamiLordus** [comment]
@Hi sonninnos any chance for version 3.8?
I'm currently checking out floppy disk games from the "preservation project" and how compatible they are with Vice.
Unfortunately, there are some games that do not want to run under version 3.7 but work under 3.8.
I would be grateful if you added the promised version 3.8 a long time ago :)

**Comment by sonninnos** [comment]
I can get to it only when I feel like it, and when I have less ongoing battles.

**Comment by KamiLordus** [comment]
Sorry to rush you and I know you have many projects (at least those related to Retroarch).
For me, Vice (next to Puae) are the most important cores for Retroarch and I will fight for their support :)
The core is great and is superior to the stand alone versions, thanks to many useful features. Although I understand that it is not as popular as, for example, MAME.

**Comment by sonninnos** [comment]
It is happening!

![retroarch_2024_09_11_18_44_03_950](https://github.com/user-attachments/assets/de31ef3d-e202-41a8-875f-94012020a988)

**Comment by KamiLordus** [comment]
Another great news :)
Thanks a lot @sonninnos.
