### ISSUE TITLE
vice_mapper_warp_mode bad default value (null)

### ISSUE THREAD

**Issue by rtomasa** [libretro/vice-libretro#501]
Hi, I found out that vice_mapper_warp_mode is set to null by default instead of "---". Probably the first pipe was unintencioned:

`SET_VARIABLES: vice_mapper_warp_mode, Hotkey > Hold Warp Mode; |---|RETROK_TAB|RETROK_RETURN|RETROK_ESCAPE|RETROK_SPACE|RETROK_QUOTE|RETROK_COMMA|RETROK_MINUS|RETROK_PERIOD|RETROK_SLASH|RETROK_0|RETROK_1|RETROK_2|RETROK_3|RETROK_4|RETROK_5|RETROK_6|RETROK_7|RETROK_8|RETROK_9|RETROK_SEMICOLON|RETROK_EQUALS|RETROK_LEFTBRACKET|RETROK_BACKSLASH|RETROK_RIGHTBRACKET|RETROK_BACKQUOTE|RETROK_a|RETROK_b|RETROK_c|RETROK_d|RETROK_e|RETROK_f|RETROK_g|RETROK_h|RETROK_i|RETROK_j|RETROK_k|RETROK_l|RETROK_m|RETROK_n|RETROK_o|RETROK_p|RETROK_q|RETROK_r|RETROK_s|RETROK_t|RETROK_u|RETROK_v|RETROK_w|RETROK_x|RETROK_y|RETROK_z|RETROK_KP0|RETROK_KP1|RETROK_KP2|RETROK_KP3|RETROK_KP4|RETROK_KP5|RETROK_KP6|RETROK_KP7|RETROK_KP8|RETROK_KP9|RETROK_KP_PERIOD|RETROK_KP_DIVIDE|RETROK_KP_MULTIPLY|RETROK_KP_MINUS|RETROK_KP_PLUS|RETROK_KP_ENTER|RETROK_KP_EQUALS|RETROK_UP|RETROK_DOWN|RETROK_LEFT|RETROK_RIGHT|RETROK_INSERT|RETROK_DELETE|RETROK_HOME|RETROK_END|RETROK_PAGEUP|RETROK_PAGEDOWN|RETROK_F1|RETROK_F2|RETROK_F3|RETROK_F4|RETROK_F5|RETROK_F6|RETROK_F7|RETROK_F8|RETROK_F9|RETROK_F10|RETROK_F11|RETROK_F12|RETROK_F13|RETROK_F14|RETROK_F15|RETROK_CAPSLOCK|RETROK_LSHIFT|RETROK_RSHIFT|RETROK_LCTRL|RETROK_RCTRL|RETROK_LALT|RETROK_RALT|RETROK_LSUPER|RETROK_RSUPER|||||||||||||||||`

**Comment by sonninnos** [comment]
Whoops, good catch, since it caused no issues here, as in it still defaults to "---".
