### ISSUE TITLE
Multiple drives support 

### ISSUE THREAD

**Issue by Vweber73** [libretro/vice-libretro#507]
Hi,

I saw that you can have a second drive using the "work disk" option, and it works.
Nonetheless, it lacks flexibility, you have to hardcode a name for each of the drive types...
What I would have liked is the m3u files behave like for the amiga core: not only for disk switching, but also for automatic insertion of each disk in a new drive. Would be quite useful for GEOS. 

Would it be possible?

Many thanks and cheers

**Comment by sonninnos** [comment]
Since practically no games can use multiple drives, it hasn't been given any thought here, but sure anything is possible..

**Comment by Vweber73** [comment]
That's why I was talking about GEOS... All the more for the C128... :)
