### ISSUE TITLE
[RPi4] lr-vice no longer supporting save states?

### ISSUE THREAD

**Issue by robbalvey** [libretro/vice-libretro#508]
I just grabbed the latest version of lr-vice from source via the RetroPie Setup Script and the most recent version of the core no longer seems to support save states. Is this correct or a bug?

**Comment by sonninnos** [comment]
Nope, nothing has changed in the core, and it still works fine, and there are no platform based exceptions. Only way to "not support" is that the frontend core info file is not correct, and the frontend thus blocks it.
