### ISSUE TITLE
EF .crt files > black screen

### ISSUE THREAD

**Issue by Gaxleep** [libretro/vice-libretro#509]
Hi, EF (Easyflash) type .crt files do not start, only the initial screen with the EF logo appears but then the screen goes black and does not proceed further. Is it possible to get around the problem?
Thank you.

**Comment by sonninnos** [comment]
All have worked here so far. Post log.

**Comment by Gaxleep** [comment]
Hi, thanks for the reply. Where can I find the log?

**Comment by sonninnos** [comment]
https://docs.libretro.com/guides/generating-retroarch-logs/#generating-logs-via-menu

**Comment by sonninnos** [comment]
Yes, that tends to happen when you have REU enabled when you should not. It would not fly with real hardware either.

Please try changing settings or testing defaults first before opening issues, especially those that you have changed.
