### ISSUE TITLE
The core does not find the vicerc file for autoload 

### ISSUE THREAD

**Issue by KamiLordus** [libretro/vice-libretro#516]
Hi @sonninnos 

It seems to me that something has been changed and the core no longer reads .vicerc files.
I have some games in .g64 and .tap format that require the basicload option.

For example:
Ultima III - Exodus.g64 requires:

  [C64SC]
AutostartBasicLoad=1

Even though I have a file in Retroarch/saves called Ultima III - Exodus.vicerc and in it:

  [C64SC]
AutostartBasicLoad=1

The core also does not read vicerc files for games in the .tap format that require:

[C64SC]
AutostartTapeBasicLoad=0

.vicerc files are located in Retroarch/saves

**Comment by sonninnos** [comment]
Post logs.

**Comment by KamiLordus** [comment]
[retroarch.log](https://github.com/libretro/vice-libretro/files/14971724/retroarch.log)

**Comment by sonninnos** [comment]
```
[libretro INFO] No configuration file found at 'E:\RetroArch\saves\VICE x64sc\Andy Capp (Europe).vicerc'.
[libretro INFO] No configuration file found at 'E:\RetroArch\saves\VICE x64sc\vicerc'.
[libretro INFO] No configuration file found at 'E:\RetroArch\system\vice\vicerc'.
```

**Comment by KamiLordus** [comment]
This is what my saves folder looks like:

![Bez tytułu](https://github.com/libretro/vice-libretro/assets/123302593/a6610c8f-4209-45be-a3ca-e3ccfe179eee)

**Comment by KamiLordus** [comment]
Ok, I've got it :) Thanks for the help, I had no idea that sorting affects this.

**Comment by KamiLordus** [comment]
If I may ask one more question.
Everything works great except Pitfall and Pitfall II - Lost Caverns.
Previously they also required .vicerc files from:
Printer4=0
Drive8Type=0

This was fixed in:
https://github.com/libretro/vice-libretro/pull/495

When I try to run it now, none of the games load (Pitfall 1 and 2). I also tried the old method with the vicerc file and it doesn't work either.

For a quick test, I'm uploading my games in .tap format
[taps.zip](https://github.com/libretro/vice-libretro/files/14972169/taps.zip)

**Comment by sonninnos** [comment]
Still work fine here as long as drive 8 is disabled with `Drive8Type=0`, and indeed I later removed the forceful disabling of drive 8 when launching tapes, which was added in that PR.

The budget TAP version of Pitfall II works with drive 8 enabled, and it also loads a lot faster. And both work even if printer is enabled with the core option, so that is redundant. And if the printer core option is enabled, it will override that vicerc disabling anyway.

**Comment by KamiLordus** [comment]
Only the start screen appears for me. Once the game has finished loading, this error appears.
![Pitfall!-240415-111302](https://github.com/libretro/vice-libretro/assets/123302593/691bb0dd-b78f-4c0f-8641-97823fe794e2)

The game should start from this point, but instead there is a blue screen and icon #8 starts flashing.
In Retroarch I have a file called Pitfall.vicerc and in it:
Drive8Type=0

I have no idea why it doesn't work.
I also leave a log of turning the game on and off.

[retroarch.log](https://github.com/libretro/vice-libretro/files/14976987/retroarch.log)

**Comment by sonninnos** [comment]
Then the vicerc is wrong since it does not show the changed conf after showing about reading the vicerc. That is precisely the symptom of the disk drive being enabled.

The config row alone does not cut it, since it also needs the header for the specific core, and always has: `[C64SC]`

**Comment by KamiLordus** [comment]
Ahh I forgot to add [C64SC]. 
Once again, thank you very much for your help.
