### ISSUE TITLE
Vice 3.8 upgrade? For Comal 80 for C128

### ISSUE THREAD

**Issue by Vweber73** [libretro/vice-libretro#518]
Hi,

I tried to use the Comal 80 cartridge for C128 and it does not work properly.
I found out that Vice 3.8 fixed this last christmas:
https://www.lemon64.com/forum/viewtopic.php?t=83718
Would it be possible to upgrade the core from Vice 3.7 to Vice 3.8? 

Many thanks in advance, best regards,

**Comment by sonninnos** [comment]
Same answer still applies: 
https://github.com/libretro/vice-libretro/issues/496

**Comment by Vweber73** [comment]
Ok, thanks!
Same remark from me as the Op of the other thread, vice and puae are the most valuable and best crafted cores! :)

**Comment by Vweber73** [comment]
Many thanks for that, much appreciated!
