### ISSUE TITLE
VIC20 autostart with PRG content

### ISSUE THREAD

**Issue by theflyingape** [libretro/vice-libretro#524]
The 3.8 update 651b05e does not autorun VIC20 BASIC/ML PRG files _unless_ after startup you press the retro hotkey for RESET with the option for Reset Type = Autostart. Attached cartridges that autostart from VIC bios boot sequence work as expected.

I tinkered with all of the 3 usual suspects: warp, autostart, and true drive emulation as well as testing for memory expansion (auto-detected from the PRG folder which still works). After each VIC startup, I type LIST and only get READY. I press my retro hotkey mapped using the END key, poof, it restarts the core and autostarts the PRG content without any intervention.

As expected, C64 works fine with CRT and disks LOAD "*",8 content -- and the single BASIC/ML game I have in PRG format called **Super Trek 64+** by Don Lekei indeed loads silently into memory and echoes "RUN:" to autostart just fine. :+1:

**Comment by sonninnos** [comment]
Finally managed to locate and fix this problem, but have to do a lot more testing with all other cores to make sure nothing else breaks..
