### ISSUE TITLE
Cartridge change problems in x128

### ISSUE THREAD

**Issue by Vweber73** [libretro/vice-libretro#525]
Whenever I change the cartridge in core options/media in 128 mode, the 128 resets but does not take into account the change, be it to choose another cartridge or to disable the cartridge.
Also, if I start x128 in C64 mode, it seems that no cartridge can be loaded, even through there is one selected in core options /media.

Another question, is there any support for the VDC while in C64 mode? I am trying to use superchip 2 v1.2 that was released recently on forum64. To run it on a 128 to benefit from the 80-column mode, you have to start it in C64 mode, not 128, and then switch the display with use C128 then select output" u7:". But this has no effect in Vice, the VDC screen remains empty. Anything I'm missing? 

Many thanks in advance and best regards

**Comment by sonninnos** [comment]
That cartridge thing behaves just the same also with C64 core, as in carts are not refreshing properly on change, and requires a full restart. Pretty sure it has always been like that at least with some carts, or did it start only after this update?

Pretty sure C128 in C64 mode means exactly that there is no C128 features available, or is it really possible with real hardware or standalone VICE? I heavily doubt that.

**Comment by Vweber73** [comment]
I don't really know how it behaved before thus update, I only got interested in cartridges recently with Comal.

When the SuperChip Cartridge is advertised as such, you need to start it in C64 mode and then use the 128 features, so it seems that was possible on real hardware. I also read that VDC was indeed accessible in C64 mode with dedicated code. I did not get this to work in the Windows Vice either, so maybe VICE core considers that C64 mode is just plain C64, with all 128 features disabled? In which case I won't be able to use the cartridge 128 features as they are meant to...

**Comment by Vweber73** [comment]
Using the Superchip II cart, Trying to list a program after redirecting the output to u7: (the VDC 80-column screen) freezes the core and generates corrupted output. So I guess Vice 3.8 does not support something that is necessary for this to work...

**Comment by theflyingape** [comment]
I recall Elite 128 diskette did AUTOBOOT from 128 mode into C64 mode, I'll verify that. I'll also have to try the Elite 128 **2.0** hack, which is supposed to run better using 128's 2mhz mode during VICII border draws. Allegedly, it was tested on THEC64 which is VICE 2.4 + REU emulation enabled.

**Comment by Vweber73** [comment]
Thanks! And actually when loading the SC II cartridge in c64 mode it says "C128 detected, which suggests that even in C64 mode some bits indicates that you are actually running a 128...

**Comment by sonninnos** [comment]
I managed to make the cartridge core option refreshing operate better, so it will be included in the next batch once I figure out the remaining annoyances.

**Comment by Vweber73** [comment]
Many thanks, much appreciated!
