### ISSUE TITLE
Hard-coded to current working directory

### ISSUE THREAD

**Issue by garbear** [libretro/vice-libretro#53]
Vice currently creates the following files in the CWD:

* vicelog.txt
* vicerc0
* FA7775AE.eeprom
* cdrom.eeprom

Vice is hard-coded to use the CWD. Should it use the libretro system directory instead? We have platforms where the frontend's directory is read-only.

First reported here: https://github.com/kodi-game/game.libretro.vice/issues/2

**Comment by rsn8887** [comment]
On the Switch, it creates vicerc0 in root and loads external palette files only from C64 folder inside root.

**Comment by rsn8887** [comment]
I just made a PR which fixes this by using system dir.
