### ISSUE TITLE
vice_xpet and vice_cbm?

### ISSUE THREAD

**Issue by telanus** [libretro/vice-libretro#58]
Is it possible to get a vice_xpet and vice_cbm2/5x0 versions of the core?

**Comment by telanus** [comment]
With @raphkoster (Thanx for doing it)  doing the xpet core, the only one still outstanding is the xcbm2

**Comment by rsn8887** [comment]
Yes. Note xpet needs the bios files from winvice installation in system/Vice/PET otherwise it doesn’t start. The other vice cores have embedded bios files, but not xpet.

**Comment by sonninnos** [comment]
Cbm2 is mostly done, so soon cometh.

**Comment by rsn8887** [comment]
Pet is already on the buildbot for all systems that have the C64 core. CBM compiles now and will be added to the buildbot in the next few days hopefully.
