### ISSUE TITLE
Core does not support save states.

### ISSUE THREAD

**Issue by modeler** [libretro/vice-libretro#6]
This is a feature request. Would it be possible to add save state support to the VICE cores please? Thank you for all your hard work thus far.

**Comment by lodgerz** [comment]
great! thank you @hiddenasbestos !

**Comment by r-type** [comment]
honestly i don't 'understand why this core live.
as this one is based on 3.1
https://github.com/r-type/sdlvice-libretro 
and support the full built-in gui/ capabilities from the upstream one.

**Comment by hiddenasbestos** [comment]
That's an excellent question. I assumed this was the current 'official' build but it seems like it's been rendered obsolete. I've posted on the libretro discord about this and I wonder if the solution is to hide this repo and make your 3.1 port the official one? Kind of above my pay-grade though :)

**Comment by hiddenasbestos** [comment]
I've posted an issue on your repo @r-type , I tried to build with MSYS2 and it doesn't link for me.

**Comment by lodgerz** [comment]
sdlvice-libretro is unusable on retroarch:
- "load content" doesn't work
- menu is not controllable from the keyboard
- save configuration doesn't work

**Comment by r-type** [comment]
Pff don't wast my time.
I don't have the above issue.
Neither the wiiu users

**Comment by rsn8887** [comment]
Fixed by https://github.com/libretro/vice-libretro/commit/9dc8a886c02e6ac2cfb4b9c9690265548aea57dd and https://github.com/libretro/vice-libretro/commit/ceefe3d6d88119f5c7b639fcc6c7fa9b9e5e7d16
