### ISSUE TITLE
The C64 Mini VICE diff.

### ISSUE THREAD

**Issue by swingflip** [libretro/vice-libretro#60]
Hi, Here is the diff between the C64 MINI vice 2.4 to the stock 2.4

You might be able to find something useful to fix up the current core.

https://github.com/swingflip/C64_mini_VICE

https://gist.github.com/swingflip/8ed86064ab580ebac9f62fe69ef10e5b

**Comment by rsn8887** [comment]
The core has been "fixed up" I'd say, no need to look at C64 MINI.
