### ISSUE TITLE
xvic core is missing essential entries in options

### ISSUE THREAD

**Issue by sneaker333** [libretro/vice-libretro#63]
The core options/gui for the xvic core are missing essential options such as memory configuration. Only being able to use the vic in unexpanded mode greatly limits what can be run. As noted in the comments the settings largely duplicate the c64 core as it allows you to select options such as SID chip (which are not applicable to the vic-20).

**Comment by sneaker333** [comment]
... although it appears that changing the vic20 model option to vic21 selects a 16k expanded vic20 ... I'll experiment and see if that'll provide me with the options I need.

**Comment by sneaker333** [comment]
The current 4 Vic models selectable in the settings are unexpanded ntsc, unexpanded pal, +16k ntsc (vic21) and unknown. The 4th model is not a specific configuration and therefore not useful. The vic21 is simply a vic20 bundled with the 16k expansion (which isn't clear from the text), but this configuration is ntsc only. I propose changing the unnecessary 4th option to +16k pal. Having the 4 combinations of ram expansion and video standard should provide the main configurations to run software properly.

I have compiled up a version with this change and it's a simple but very useful addition without making bigger changes to accommodate different memory configurations.

**Comment by rsn8887** [comment]
Can you make a Pull Request?

**Comment by sneaker333** [comment]
I've never used git before ... I'll look into what I need to do. There's a few fixes which would help out the vic20 core and I'll try and provide a few minor changes which should allow it to run any games I've found. So far there are the following issues I hope I can help with -

1) Vic20 keymap is missing - the C64 keymap is used instead which causes a number of keys to map incorrectly
2) The file extensions in the info file are not up-to-date with those defined in the core
3) Missing an expanded PAL model as outlined above.
4) There is support in the core for using a command file, which allows any missing settings to be defined/overridden - this should allow any vice setting to be changed regardless of what is supported by the gui. However, gui options are being applied after the command line is parsed, which can reset the settings back. With this working then the existing models do not need to be changed as you can define any hardware config in the cmd file.

I'll have a look at git and then I'll see if I can get these tweaks in.

**Comment by rsn8887** [comment]
What is still missing? The PAL expanded type? I think not even WinVice standalone has that model type, or does it? How is it called?

**Comment by sneaker333** [comment]
Hi,

I've just noticed that there has been a lot of changes to the Vice core recently - I'll have a look and see how these changes have affected my suggestions. I know that the 'non-existent' model suggestion doesn't exist in other versions of vice, but in a standard desktop build you could always use the command line options or the gui to change the ram configuration and pal/ntsc mode. As the libretro core is usually run from retroarch or similar then you are restricted by the core options. Although it's possible to add a lot more core options to provide access to those settings, for ease of use then you only really require the 4 combinations of unexpanded, 16K expanded, pal & ntsc. 3 of those conditions are covered by the real vic20 models listed - a 'fantasy' 4th model would be the easiest way of achieving the 4th combination of settings. I also discovered that it was not possible to run a MegaCart cartridge, although it's supported by Vice. I had a working hack which allowed it to work under RetroArch - I'll have another look at these things now all the changes are in place and see if these tweaks are redundant now otherwise I'll put together a pull request

**Comment by sonninnos** [comment]
It is possible to use some of the missing options with system/vice/vicerc.

I use it for attaching an Action Replay MK4 Cartridge that does not interfere with autostart, like so:
`
[C64SC]
CartridgeFile="path"
`

**Comment by sneaker333** [comment]
Hi Sonninnos,

It's great to see you've contributed a lot of updates to this core - My first computer was the Vic20 and obviously my second was the C64, so it means a lot to me to have those running under Retroarch. I did have a play with a few changes, but not being familiar with Vice or the structure of Libretro cores it seemed a bigger job than I was prepared (or qualified) to get in to - I did learn more than I really wanted to in the process though :-) I'll have a play with the new cores and see what I can contribute where some issues may still remain.

Unfortunately there doesn't appear to be resource settings for Vic20 memory blocks or video modes - so the vicerc route doesn't appear to help in this issue I'm afraid.

I did get around to playing with the .cmd file support previously, where you can store a vice command line in a text file and launch that. This is really useful as you can expose all of vice's features using that. The problem I discovered was that the core options were being applied after the command line had been parsed - this led to some settings being overwritten by the core options, and for the vic this is critical as it resets the memory and video mode settings. I had a working hack to see if it was possible - I'll have a check if a fix is still needed.

Many thanks for your additional work on this core.

**Comment by sonninnos** [comment]
Much appreciated! This Vice core assault is the first contributing experience for me, and the only background I have is Web based server+client bidness, so there was and is a lot to learn and figure out.

I think we can work the missing options out somehow, but please provide a way they can be done with stand-alone Vice first, because I don't have the experience nor time to find out.
