### ISSUE TITLE
add x64sc version to buildbot 

### ISSUE THREAD

**Issue by eadmaster** [libretro/vice-libretro#66]
The "x64sc" version  is the most accurate [according to the official docs](http://vice-emu.sourceforge.net/vice_toc.html#TOC6).

**Comment by sonninnos** [comment]
The makefile was busted so it would not build at all, but I got it fixed in my fork.

**Comment by rsn8887** [comment]
Can you make a PR with your fix? Thank you!

**Comment by rsn8887** [comment]
Where do you want it added? Windows?

**Comment by rsn8887** [comment]
I added it to all platforms that have the x64 core now.
