### ISSUE TITLE
Can't switch tape side / image nor "rewind"

### ISSUE THREAD

**Issue by LordArchantos** [libretro/vice-libretro#67]
Tape games with more than one side / tape cannot be played. At the moment it seems using an m3u with .tap files doesn't work "properly". While it does load the correct first tape image, at least switching the image during a game loading using RetroArch's disk controls doesn't stop the game continuing to load as if the tape hasn't been swapped.

But even if that worked, currently if you enable status bar, you can also see that when a game asks you to e.g. "switch to side 2 and press fire" and you do, the tape counter continues from the reading it was at as it doesn't reset to zero (i.e. start of tape image). Datassette controls would be useful to have exposed in general as well, but especially as there are games that require you to rewind to a specific spot e.g. after losing all lives in a later level.

**Comment by sonninnos** [comment]
Here is a new PR for you to try out if everything suits the needs: https://github.com/libretro/vice-libretro/pull/101
