### ISSUE TITLE
Joy2 is always enabled by default

### ISSUE THREAD

**Issue by rockaddicted** [libretro/vice-libretro#8]
Hi,
I'm testing the [current master](https://github.com/libretro/vice-libretro/commit/2bfda7bfdc7c3de7b5f4c31edfaf4bb1e8253fc8) and everytime that I start a game, even with only 1 gamepad connected, Joy2 is enabled by default.  
So I have to manually switch to Joy1 (using L2 button or using the gui option) to be able to play with my gamepad.

**Comment by modeler** [comment]
Most Commodore 64 games used Port Two by default, it was normal for Player One to keep their joystick in there so I think this is the correct default value. It would be nice to have this in the core options though, so you could change the default to Port One and make it persistent.

**Comment by r-type** [comment]
yes core option could be added for that , have to look at

**Comment by rockaddicted** [comment]
Ok, I don't really know this hardware, so I didn't know that was the normal behavior.
So no problem for me to keep Joy2 as default value.
And indeed, a core option to set and save the setting can be a good alternative.

**Comment by rsn8887** [comment]
I added a core option for this (quick menu - options)

**Comment by rsn8887** [comment]
This issue can be closed it was fixed around April 2018.
