### ISSUE TITLE
New virtual keyboard last row & column

### ISSUE THREAD

**Issue by sonninnos** [libretro/vice-libretro#81]
Last row & column suddenly can't be selected anymore.

With mouse yes, joypad no.

**Comment by rsn8887** [comment]
This was fixed just today. It was my fault.

**Comment by rsn8887** [comment]
I fixed it in these two commits:
https://github.com/libretro/vice-libretro/commit/7d6eec168c691698934da6ecfb70cd33a2e6f339
https://github.com/libretro/vice-libretro/commit/00c65ea4cf03743cf0a5b7f262598d3922e14334

**Comment by rsn8887** [comment]
If you just `git pull --rebase upstream master` you can get the fix already now.

**Comment by rsn8887** [comment]
Ok the new nightly just came out. So if you now go to Online Updater->Update Cores and select the Commodore 64 core or any Vice core, the virtual keyboard will work again :)
