### ISSUE TITLE
Add support for PSP

### ISSUE THREAD

**Issue by bmaupin** [libretro/vice-libretro#93]
Now that this core has been upgraded to VICE 3.3, I think it'd be feasible to add support for the PSP:

> I think resid emulation has become much faster at some point recently. For example, in 3.2 it is much faster than in 3.0, it runs even on a PSP without slowdown, using 3.2.

https://github.com/libretro/vice-libretro/issues/41#issuecomment-509828861

Thanks!

**Comment by rsn8887** [comment]
No this was something else.

Resid is still slow. It just is.

**Comment by rsn8887** [comment]
Correction I think with @sonninnos latest update to include the “resid resampling” Option set to “fast” resid will probably become fast again even on Vita. So PSP might be a viable platform for this core.

**Comment by bmaupin** [comment]
Thanks! I've got a branch with a working build here:

https://github.com/bmaupin/vice-libretro/tree/93-add-support-for-psp

I only made the bare minimum changes to get it working.

Is this something worth merging? Loading games seems to work, but the audio is very choppy, no doubt because of what you mentioned. I set *ReSID sampling* to *Fast* but unfortunately it's still very slow and choppy.

**Comment by bmaupin** [comment]
... I guess it won't hurt anything to merge these changes so PSP builds work, but until they're more performant I wouldn't recommend enabling them by default on the buildbot server.

My best guess is pspvice still has other optimisations for the PSP that aren't in this core. I've built a few other cores for the PSP and I've run into similar results. From what little I know about the subject it seems that the PSP simply just doesn't have a lot of power and requires a lot of optimisations to be able to run a lot of these emulators, which is why the standalone emulators seem to perform so much better than the libretro cores. Ideally it would be great to merge the optimisations from the standalone emulators into the cores, but that's not something that I have the expertise to do.
