### ISSUE TITLE
.Nib file support?

### ISSUE THREAD

**Issue by goedzo** [libretro/vice-libretro#97]
I've used the nightly build of this core from 2019-08-02.

I have .nib files in my collection and when I try to load these with the core the following is in the logs:
[libretro ERROR] Palette not found: `mps803.vpl'.
[libretro ERROR] Cannot load palette file `mps803.vpl'.
[libretro ERROR] Palette not found: `nl10.vpl'.
[libretro ERROR] Cannot load palette file `nl10.vpl'.
[libretro ERROR] Palette not found: `1520.vpl'.
[libretro ERROR] Cannot load palette file `1520.vpl'.
[libretro ERROR] 2000 ROM image not found. Hardware-level 2000 emulation is not available.
[libretro ERROR] 4000 ROM image not found. Hardware-level 4000 emulation is not available.
[libretro ERROR] Import GCR: Unknown GCR image version 49.
[libretro ERROR] Cannot open file `J:\RetroFE\Roms\Commodore 64\roms\\Addams Family, The (USA, Europe).nib'
[libretro ERROR] CRT header invalid.
[libretro ERROR] Invalid size of 'J:\RetroFE\Roms\Commodore 64\roms\\Addams Family, The (USA, Europe).nib': 336126
[libretro ERROR] `J:\RetroFE\Roms\Commodore 64\roms\\Addams Family, The (USA, Europe).nib' is not a valid file.

Is .nib supported with this core, or not?

**Comment by sonninnos** [comment]
Hmm, I see no mention of nib in Vice manual, so perhaps best to convert the file to a supported one and/or get another version.

**Comment by goedzo** [comment]
Yep, looks like your right! Files must be converted with nib tools:
https://c64preservation.com/nibtools
 
NIBTOOLS is a disk transfer program designed for copying original disks 
   and converting into the G64 and D64 disk image formats. These disk images
   may be used on C64 emulators like VICE or CCS64 [2,3] and can be transferred
   back to real disks.

So I will close the issue, and leave this comment for everyone to see :)
